# GENERATED by tools/gen_abi.py — DO NOT EDIT. One table, three
# projections: private copies of these addresses are forbidden.
BANK_L0 = 4  # legacy alias for BANK_SEG (two-bank re-cut 2026-08-13)
BANK_SEG = 4  # sideways bank A: seg headers+DIRs, verts, recips, VWHC, TABL0 — held for seg stages 1-4
BANK_C = 6  # sideways bank: clipper + rasteriser + HUD
BANK_L2 = 7  # legacy alias for BANK_WALK
BANK_WALK = 7  # sideways bank B: node SoA, L8/AE/VATOX, bbox, CPM, rcache, ANIM CFG — held for the whole BSP walk
MAIN_BASE = 0x2C00  # engine CODE region head (cfg-anchored; MAIN first)
HUD_ENTRY = 0xA400  # hud_draw (bank C window)
BCA_AB = 0x0062  # view angle byte — ZP (zp_buf's slot, freed with span_read 2026-07-26; NOT $64 — that is zp_bv_entry's HI byte, the drivers seed it); poked per frame by driver/harness; vxc_ab aliases it; zp.inc aliases bca_ab = BCA_AB
SQR_BASE = 0x1A00  # quarter-square tables, CONSOLIDATED $1A00-$1DFF 2026-08-09 (the retired vsync-journal page + the freed VCACHE_VALID page): lo,2lo then hi,2hi — one contiguous quad, one address, both builds
SQR_LO = 0x1A00  # qsqr lo bytes (f 0..255)
SQR2_LO = 0x1B00  # qsqr lo bytes (f 256..510)
SQRH_BASE = 0x1C00  # quarter-square HI pages ($1C00/$1D00) — UNFORKED into the $1A00-$1DFF quad 2026-08-09: the $0200 OS-page boot-staging dance died (page 2 freed — the tube client owns it); flat $1E00 freed for LDATA
SQR_HI = 0x1C00  # qsqr hi bytes (f 0..255)
SQR2_HI = 0x1D00  # qsqr hi bytes (f 256..510)
DRV_ORG = 0x2000  # walk/anim driver entry (!BOOT CALLs this)
DRV_VARS = 0x2180  # walk driver variable block (layout below)
DV_ANGIDX = 0x2180  # view angle index 0..63 (angle byte = idx*4)
DV_BACKHI = 0x2181  # hidden-buffer page hi ($58/$6C)
DV_PXF = 0x2182  # player x 8.8 prescaled, 24-bit: frac
DV_PXL = 0x2183  # ... int lo
DV_PXH = 0x2184  # ... int hi
DV_PYF = 0x2185  # player y frac
DV_PYL = 0x2186  # ... int lo
DV_PYH = 0x2187  # ... int hi
DV_JIDX = 0x2188  # vsync journal index
DV_HUD_EN = 0x2189  # debug HUD on/off (H toggles)
DV_HUD_PREV = 0x218A  # H-key debounce state
DRV_GLUE = 0x21A0  # anim/HUD glue pocket
DRV_TAB = 0x2200  # sincos table overlay: 64 x 8 bytes
DRV_CLR = 0x2400  # unrolled clears + input block
D_ENABLE = 0x05FE  # forward-coherence bbox cache master switch
D_FWD = 0x05FF  # per-frame flag: move was forward-only
VXC_STATE = 0x0700  # THE BITMAP PAGE: VCACHE_VALID+VDONE+VXC_VALID+RCACHE_COMPUTED (boot zeroes the whole page)
VXC_STATE_LEN = 0x0100  # bytes to zero at boot (the whole bitmap page)
VXC_ENABLE = 0x05DB  # translation vertex cache switch
RCACHE_STATE = 0xAF00  # rotation cache header+bitmaps (flat: $F100; carve freed 2026-07-15)
RCACHE_STATE_FLAT = 0x7268
RCACHE_STATE_LEN = 0x0089  # bytes to zero at boot
RCACHE_ENABLE = 0xAF88  # rotation-coherence bca cache switch (STATE+$88)
RCACHE_ENABLE_FLAT = 0x72F0
CPM_BASE = 0xA600  # corner-phi memo: 128-slot xor hash, 3 pages ($5500-$57FF flat, ending exactly at the screen). Banked $A600 in bank WALK (two-bank re-cut 2026-08-13). SCAR: an earlier home sat ON ROM_BBOX_C and the memo stores SHREDDED the corner planes (black screen after walking; banked gates compare engine-vs-itself so both sides corrupted identically). Scan the MERGED map before claiming space.
CPM_BASE_FLAT = 0x7E00
CPM_KDXL = 0xA600  # memo key: corner dx lo
CPM_KDXH = 0xA680  # ... dx hi; DOUBLES as validity: plane ships $80-filled ($80 = impossible dx hi), so there is no EP plane
CPM_KDYL = 0xA700  # ... dy lo
CPM_KDYH = 0xA780  # ... dy hi
CPM_PSIL = 0xA800  # memo value: psi lo
CPM_PSIH = 0xA880  # ... psi hi (last plane: memo ends at CPM_BASE+$300)
SCREEN0 = 0x5800  # framebuffer 0 (flat: harness FB $EA00-$FDFF)
SCREEN0_FLAT = 0xEA00
SCREEN1 = 0x6C00  # framebuffer 1 (flat: single buffer)
SCREEN1_FLAT = 0xEA00
