# GENERATED by tools/gen_abi.py — DO NOT EDIT. One table, three
# projections: private copies of these addresses are forbidden.
BANK_L0 = 4  # sideways bank: level data (SoA, seg_hdr, FHCH, TABL0)
BANK_C = 6  # sideways bank: clipper + rasteriser + HUD
BANK_L2 = 7  # sideways bank: angle/bbox/recip/verts/RCACHE/VWHC/CFG
ENGINE_JT = 0x2C00  # driver-facing jump table = MAIN segment head (link-asserted)
ENGINE_JT_FLAT = 0x3670
JT_VIEW_SETUP = 0x2C09  # br_view_setup
JT_RENDER_FRAME = 0x2C15  # br_render_frame
JT_INIT_FRAME = 0x2C1B  # br_init_frame
JT_ANIM_TICK = 0x2C1E  # anim_tick (PAGE BANK_L2 first)
JT_ANIM_INIT = 0x2C21  # anim_init (PAGE BANK_L2 first)
CLIP_JT = 0x8000  # clipper jump table; entry 0 = span_init
CLIP_JT_FLAT = 0x2000
HUD_ENTRY = 0xA400  # hud_draw (bank C window)
BCA_WS = 0x1B40  # angle-module bbox workspace (box vals at +$10..$17)
BCA_WS_FLAT = 0xFA00
BCA_AB = 0x1B6F  # view angle byte, poked per frame by driver/harness
SQR_BASE = 0x1C00  # quarter-square tables: lo,hi,2lo,2hi = 4 pages
SQR_BASE_FLAT = 0xA500
SQR_LO = 0x1C00  # qsqr lo bytes (f 0..255)
SQR2_LO = 0x1D00  # qsqr lo bytes (f 256..510)
SQR_HI = 0x1E00  # qsqr hi bytes (f 0..255)
SQR2_HI = 0x1F00  # qsqr hi bytes (f 256..510)
DRV_ORG = 0x2000  # walk/anim driver entry (!BOOT CALLs this)
DRV_VARS = 0x2180  # walk driver variable block (layout below)
DV_ANGIDX = 0x2180  # view angle index 0..63 (angle byte = idx*4)
DV_BACKHI = 0x2181  # hidden-buffer page hi ($58/$6C)
DV_PXF = 0x2182  # player x 8.8 prescaled, 24-bit: frac
DV_PXL = 0x2183  # ... int lo
DV_PXH = 0x2184  # ... int hi
DV_PYF = 0x2185  # player y frac
DV_PYL = 0x2186  # ... int lo
DV_PYH = 0x2187  # ... int hi
DV_JIDX = 0x2188  # vsync journal index
DV_HUD_EN = 0x2189  # debug HUD on/off (H toggles)
DV_HUD_PREV = 0x218A  # H-key debounce state
DRV_GLUE = 0x21A0  # anim/HUD glue pocket
DRV_TAB = 0x2200  # sincos table overlay: 64 x 8 bytes
DRV_CLR = 0x2400  # unrolled clears + input block
D_ENABLE = 0x05FE  # forward-coherence bbox cache master switch
D_FWD = 0x05FF  # per-frame flag: move was forward-only
VXC_STATE = 0x05A0  # VXC valid bitmap + state block
VXC_STATE_LEN = 0x0060  # bytes to zero at boot
VXC_ENABLE = 0x05DB  # translation vertex cache switch
RCACHE_STATE = 0xB460  # rotation cache header+bitmaps (RCACHE+$760)
RCACHE_STATE_FLAT = 0x5760
RCACHE_STATE_LEN = 0x0089  # bytes to zero at boot
RCACHE_ENABLE = 0xB4E8  # rotation-coherence bca cache switch (RCACHE+$7E8)
RCACHE_ENABLE_FLAT = 0x57E8
JBASE = 0x1A00  # vsync journal (dead boot-loader memory)
SCREEN0 = 0x5800  # framebuffer 0
SCREEN1 = 0x6C00  # framebuffer 1
