# GENERATED by tools/gen_abi.py — DO NOT EDIT. One table, three
# projections: private copies of these addresses are forbidden.
BANK_L0 = 4  # legacy alias for BANK_SEG (two-bank re-cut 2026-08-13)
BANK_SEG = 4  # sideways bank A: seg headers+DIRs, verts, recips, VWHC, TABL0 — held for seg stages 1-4
BANK_C = 6  # sideways bank: clipper + rasteriser + HUD
BANK_L2 = 7  # legacy alias for BANK_WALK
BANK_WALK = 7  # sideways bank B: node SoA, L8/AE/VATOX, bbox, CPM, rcache, ANIM CFG — held for the whole BSP walk
MAIN_BASE = 0x2500  # engine CODE region head (cfg-anchored; MAIN first). $2A00 -> $2600 2026-08-19: the -$400 window slide that took the pm_frame code out of bank B — strip $1600, window $1A00-$25FF, CODE $2600 with PMB1-4 appended identically in both builds. $2600 -> $2500 2026-08-23: PMOVE+PMH are 1,728 B and stopped at $24FF, leaving the PMOVE region a dead last page; CODE takes it (+256 B) and the window shrinks to $1A00-$24FF. Both cfgs move together — bottom-22K identity.
HUD_ENTRY = 0xA400  # hud_draw (bank C window)
BCA_AB = 0x0062  # view angle byte — ZP (zp_buf's slot, freed with span_read 2026-07-26; NOT $64 — that is zp_bv_entry's HI byte, the drivers seed it); poked per frame by driver/harness; vxc_ab aliases it; zp.inc aliases bca_ab = BCA_AB
SQR_BASE = 0x0200  # quarter-square tables: lo,2lo then hi,2hi — one contiguous quad $0200-$05FF, one address, both builds. Moved from $1A00 2026-08-18: pure-function data belongs in the UNSHIPPABLE pages (OS-owned until takeover) — it is GENERATED at boot by the fill at the top of anim_init, never loaded, and the shippable pages it vacated took COLPORT and the pool, killing every boot copy-dance.
SQR_LO = 0x0200  # qsqr lo bytes (f 0..255)
SQR2_LO = 0x0300  # qsqr lo bytes (f 256..510)
SQRH_BASE = 0x0400  # quarter-square HI pages ($0400/$0500). The 2026-08-09 note about the $0200 staging dance dying is history twice over: the quad is back on the OS pages, but BOOT-GENERATED now, so there is no dance to die.
SQR_HI = 0x0400  # qsqr hi bytes (f 0..255)
SQR2_HI = 0x0500  # qsqr hi bytes (f 256..510)
DRV_ORG = 0x1A00  # walk/anim driver entry (!BOOT CALLs this). $1E00 -> $1A00 2026-08-19 (the -$400 window slide, bank-B code eviction): the exception window is $1A00-$25FF — banked walk_drv+PMOVE, flat VXC_YLO/YHI + CPM keys + records + PM_SCRATCH + PMH.
DRV_VARS = 0x1B80  # walk driver variable block (layout below)
DV_ANGIDX = 0x1B80  # view angle index 0..63 (angle byte = idx*4)
DV_BACKHI = 0x1B81  # hidden-buffer page hi ($58/$6C)
DV_PXF = 0x1B82  # player x 8.8 prescaled, 24-bit: frac
DV_PXL = 0x1B83  # ... int lo
DV_PXH = 0x1B84  # ... int hi
DV_PYF = 0x1B85  # player y frac
DV_PYL = 0x1B86  # ... int lo
DV_PYH = 0x1B87  # ... int hi
DV_JIDX = 0x1B88  # vsync journal index
DV_HUD_EN = 0x1B89  # debug HUD on/off (H toggles)
DV_HUD_PREV = 0x1B8A  # H-key debounce state
DRV_GLUE = 0x1BA0  # anim/HUD glue pocket
DRV_CLR = 0x1C00  # input block + flip scheduler; the unrolled framebuffer clears moved to BANK C 2026-08-16, and the whole driver slid $2200 -> $2100 with DRV_ORG 2026-08-17 (2026-08-14: the sincos overlay moved to bank A $BA00 with STEPTAB/USEVEC; the driver packs below the engine PMOVE region)
D_ENABLE = 0x19FE  # forward-coherence bbox cache master switch
D_FWD = 0x19FF  # per-frame flag: move was forward-only
VXC_STATE = 0x0700  # THE BITMAP PAGE: VCACHE_VALID+VDONE+VXC_VALID+RCACHE_COMPUTED (boot zeroes the whole page)
VXC_STATE_LEN = 0x0100  # bytes to zero at boot (the whole bitmap page)
VXC_ENABLE = 0x19DD  # translation vertex cache switch (scalars block $05xx -> $1Dxx sqr swap -> $19xx window slide -> $19DB->$19DD 2026-08-22 to clear the span pool 15th/16th planes; vxc_prev_ab follows it)
RCACHE_STATE = 0xAF00  # rotation cache header+bitmaps (flat: $F100; carve freed 2026-07-15)
RCACHE_STATE_FLAT = 0x7268
RCACHE_STATE_LEN = 0x0089  # bytes to zero at boot
RCACHE_ENABLE = 0xAF88  # rotation-coherence bca cache switch (STATE+$88)
RCACHE_ENABLE_FLAT = 0x72F0
CPM_BASE = 0xA600  # corner-phi memo: 128-slot xor hash, 6 planes. This is the KEY head — 4 key planes, $200 long (the value planes hang off CPM_PSI_BASE, split out flat-side 2026-08-17). Banked $A600 in bank WALK (two-bank re-cut 2026-08-13). SCAR: an earlier home sat ON ROM_BBOX_C and the memo stores SHREDDED the corner planes (black screen after walking; banked gates compare engine-vs-itself so both sides corrupted identically). Scan the MERGED map before claiming space.
CPM_BASE_FLAT = 0x1F00
CPM_KDXL = 0xA600  # memo key: corner dx lo
CPM_KDXH = 0xA680  # ... dx hi; DOUBLES as validity: plane ships $80-filled ($80 = impossible dx hi), so there is no EP plane
CPM_KDY_BASE = 0xA700  # dy key planes head (banked: inline; flat: the page RECIP_S left)
CPM_KDY_BASE_FLAT = 0x1E00
CPM_KDYL = 0xA700  # ... dy lo
CPM_KDYH = 0xA780  # ... dy hi
CPM_PSI_BASE = 0xA800  # psi value planes head (banked: inline after the keys; flat: off the $2B00 page CODE took, into the free run above the recip tables)
CPM_PSI_BASE_FLAT = 0xD700
CPM_PSIL = 0xA800  # memo value: psi lo
CPM_PSIH = 0xA880  # ... psi hi (last plane; the key planes end at CPM_BASE+$200)
COLIDX_BASE = 0xAF8A  # collision blockmap: 36 x (u16 list addr, u8 count) + the u8 lists (banked: $B4A4 -> $AB00 -> $AF8A 2026-08-15 — off the SSMASK staging page, then off the rcache PSI PLANES $A900-$AEFF; now after RCACHE_STATE, ends $B197)
COLIDX_BASE_FLAT = 0x7600
COLSEG_BASE = 0xB8C0  # collision segments: n x 8 (x1,y1,dx,dy raw s16 LE, center-relative)
COLSEG_BASE_FLAT = 0x7810
SS_VZ_BASE = 0x8D00  # per-subsector prescale(floor+41) (s8). Banked $8D00 since 2026-08-19: the fifth of the five adjacent SS planes in bank B ($8900 PC, $8A00 SI, $8B00 FH, $8C00 CH, $8D00 VZ)
SS_VZ_BASE_FLAT = 0xE750
MV_SS_ID = 0xBFC6  # mover-subsector probe list: <=8 ids, $FF-padded (pmove scans it twice per move — the 2026-08-19 claw-back that kept SS_PLO plain)
MV_SS_ID_FLAT = 0xE980
MV_SS_INFO = 0xBFCE  # parallel info bytes, classic SS_INFO format (mover idx, b7 = ceiling)
MV_SS_INFO_FLAT = 0xE988
MV_MINPASS = 0xBFC0  # per-mover min passable door pos (fh + 56, prescaled)
MV_MINPASS_FLAT = 0xE910
COLPORT_BASE = 0x1600  # P_CheckPosition aggregation ports: 42 x 12 (x1,y1,dx,dy s16 + ob_vz + ot_ps + mover + wall-angle). Strip head since the 2026-08-19 window slide: LOW / the tube CODE file load from LOW_BASE = here, so the ports SHIP DIRECTLY.
LOW_BASE = 0x1600  # first shipped byte of the LOW disc image / tube CODE file / bare-boot copy (the strip head)
SPAN_POOL = 0x1800  # clipper span pool block head (13 x $20 fields; arith.s POOL derives from this)
PMOVE_BASE = 0x1E40  # PMOVE region head (banked cfg anchor; build_anim_ssd asserts driver_end <= this)
COL_N_SOLID = 0x00C7  # collision indices >= this are ports (colmap asserts the count)
PM_MOMX = 0x17F8  # RETIRED 2026-08-22 with momentum; the COLPORT tail, left declared so the slot stays reserved and pm_fuzz can assert it stays zero
PM_MOMY = 0x17FA  # RETIRED with PM_MOMX (derives — a hard $03FA literal here survived the 2026-08-18 move and cost a red pm_fuzz)
PM_TURNREM = 0x17FC  # sub-step rotation fraction, Q8 — carries the frame-rate-compensated turn across frames (was the 35Hz tic remainder)
USETAB_BASE = 0xBE00  # use + walkover line tables (u8 n, n x 9: x1,y1,dx,dy s16 + action); banked home is BANK A since the slide arc — pmove_use pages SEG for the list reads
USETAB_BASE_FLAT = 0xE918
SCREEN0 = 0x5800  # framebuffer 0 (flat: harness FB $EA00-$FDFF)
SCREEN0_FLAT = 0xEA00
SCREEN1 = 0x6C00  # framebuffer 1 (flat: single buffer)
SCREEN1_FLAT = 0xEA00
