#!/usr/bin/env python3
"""Build doom_walk.ssd — THE dual-mode game disc (2026-07-21: the
separate doom_tube.ssd is gone; !BOOT detects a 6502 copro and loads
the Tube version, else chains the banked WALK loader).

The parasite runs the FLAT engine build VERBATIM: this script constructs
the full py65 64K image exactly as the regression harness does
(BspRender6502.__init__: engine link + tables + packed E1M1), then makes
exactly three surgical changes:
  - the NJ rasteriser blob at $A900 is replaced by the Tube emitters
    (tube/emit.asm) — dcl's des_diag JMP $A900 needs no patch at all;
  - plot_h and plot_v entries are poked to JMP $A910/$A920 (the h/v
    emitters). Everything else is byte-identical to the flat build.
The occupied regions are chunked into DFS data files that the copro
bootstrap (tube/tubedrv.asm) *LOADs across the Tube via the parasite OS
before killing the host OS with its raw RUN HOSTT.

Files: !BOOT (tube/detect.asm), COPROT (tubedrv: bootstrap + driver +
tables), HOSTT (tube/hostg.asm: carousel + plot_h/v + real NJ), CODE +
DATA (the two parasite loads), then the banked side from
build_walk_ssd.banked_files() (WALK/BANK0-2/LOW).
"""
import os, subprocess, sys

# THE COPRO IS A 65C02 -- and span_clip_6502/symmap bind DOOM_CPU at
# IMPORT time, so it must be set BEFORE any project import or the
# parasite silently ships the NMOS engine against C02 maps (caught by
# the pure-concat gate 2026-09-02).  The banked side is immune: its
# variants build in subprocesses with their own env (_banked_variant).
os.environ['DOOM_CPU'] = '65c02'

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)
os.environ.setdefault('SDL_VIDEODRIVER', 'dummy')
os.environ.setdefault('PYGAME_HIDE_SUPPORT_PROMPT', '1')

SECTOR = 256
TOTAL_SECTORS = 800
SPAWN_X, SPAWN_Y = 1056, -3616
SPAWN_ANGIDX = 16               # angle byte 64, walk_drv's spawn facing
RESIDENT = 0xF600               # the glue+emitters block: top of memory,
                                # under the client OS (shipped inside DATA)


def write_ssd(files, path):
    disc = bytearray(TOTAL_SECTORS * SECTOR)
    disc[0:8] = b'DOOMTB\x00\x00'
    n = len(files); assert n <= 31, n
    disc[SECTOR + 5] = n * 8
    nxt = 2; secs = []
    for _, _, _, data in files:
        ns = (len(data) + SECTOR - 1) // SECTOR
        secs.append((nxt, ns)); nxt += ns
    total = nxt; assert total <= TOTAL_SECTORS
    disc[SECTOR + 6] = (2 << 4) | ((total >> 8) & 3)
    disc[SECTOR + 7] = total & 0xFF
    for i, (name, load, exe, data) in enumerate(files):
        ss, _ = secs[i]; off = (i + 1) * 8
        disc[off:off+7] = name.encode().ljust(7, b' ')[:7]
        disc[off + 7] = ord('$')
        m = SECTOR + (i + 1) * 8
        disc[m+0] = load & 0xFF; disc[m+1] = (load >> 8) & 0xFF
        disc[m+2] = exe & 0xFF;  disc[m+3] = (exe >> 8) & 0xFF
        disc[m+4] = len(data) & 0xFF; disc[m+5] = (len(data) >> 8) & 0xFF
        disc[m+6] = ((ss>>8)&3) | (((load>>16)&3)<<2) | \
                    (((len(data)>>16)&3)<<4) | (((exe>>16)&3)<<6)
        disc[m+7] = ss & 0xFF
        disc[ss*SECTOR: ss*SECTOR + len(data)] = data
    open(path, 'wb').write(disc)
    print(f"Built {path}: {n} files, {total}/{TOTAL_SECTORS} sectors")
    for i, (name, load, exe, data) in enumerate(files):
        print(f"  {name:7s} &{load:05X}  {len(data):>5} B  sec {secs[i][0]}")


def asm(src, out):
    subprocess.run([os.path.join(ROOT, 'beebasm'), '-i', src],
                   cwd=ROOT, check=True)
    with open(os.path.join(ROOT, out), 'rb') as f:
        data = f.read()
    os.remove(os.path.join(ROOT, out))
    return data


def write_tube_syms():
    """Regenerate tube/tube_syms.inc from the CURRENT engine map (and
    under the CURRENT DOOM_CPU env). The py65 tube tests call this too:
    a stale syms file after any engine-layout slide assembles tubedrv
    against dead addresses (the 2026-08-10 anim_tick crash class)."""
    import doom_wireframe as dw
    import symmap, abi

    def fsym(name):
        return symmap.sym(name)

    px88 = int((SPAWN_X - dw.MAP_CENTER_X) * 256 / dw.PRESCALE) & 0xFFFFFF
    py88 = int((SPAWN_Y - dw.MAP_CENTER_Y) * 256 / dw.PRESCALE) & 0xFFFFFF
    vz = dw._prescale_height(dw.player_floor(SPAWN_X, SPAWN_Y) + 41) & 0xFF
    # letter); a class entry ending in FE/FF would let the packet fake the
    # host's FE FE FE FE / FF FF FF FF markers.
    with open('tube/tube_syms.inc', 'w') as f:
        f.write("\\ GENERATED by tube/build_tube_game.py - DO NOT EDIT.\n")
        for t, s in (('T_VIEW_SETUP', 'view_setup'),
                     ('T_SPAN_INIT', 'span_init'),
                     ('T_RENDER_FRAME', 'render_frame'),
                     ('T_TAIL_POSTRC', 'bca_tail_postrc'),
                     ('T_BOX_CLASSIFY', 'box_classify'),
                     ('T_ANIM_INIT', 'anim_init'),
                     ('T_ANIM_TICK', 'anim_tick'),
                     ('T_ANIM_FIELDS', 'ANIM_FIELDS'),
                     ('T_ANIM_ENABLE', 'ANIM_ENABLE'),
                     # HUD class letter (2026-09-04): the packet's last byte
                     # these two class entries, as src/hud.s does
                     # PMOVE: the parasite runs the SAME DOOM collision /
                     # slide / frame-rate-compensated walk as walk_drv
                     # (2026-08-23).  pm_frame owns rotation, position,
                     # slide and D_FWD; pmove_zonly re-derives z so the
                     # copro rides live lifts too.
                     ('T_PM_FRAME', 'pm_frame'),
                     ('T_PMOVE_ZONLY', 'pmove_zonly'),
                     ('T_PM_VZ', 'pm_vz'),
                     # SPACE 'use': without it every DR door on the map is
                     # shut forever (anim_sectors: "shut until used"), which
                     # is not a rendering bug but a missing input path.
                     ('T_PMOVE_USE', 'pmove_use'),
                     ('T_PM_UX', 'pm_ux'),
                     # O toggle (2026-09-02 two-byte mask): the edge-free
                     # flip body of obj_key -- the copro edge-detects the
                     # host-shipped level itself
                     ('T_OK_FLIP', 'ok_flip'),
                     # THE VIEW BLOCK.  tubedrv hand-baked these as &00,
                     # &01, &02, &03, &04, &05..&0A, &9D, &9E -- the zero
                     # page addresses they happened to have.  Zero page is
                     # linker-allocated and tools/zprotate rotates cold
                     # bytes OUT of it, so those literals rotted silently:
                     # zp_br_px and zp_br_py went absolute on 2026-08-31
                     # and the driver started writing the pose fraction
                     # into the s16 clipper's LC_OY1 anchors instead.
                     # The fractions are read ~0.1 times a frame, so
                     # nothing failed until the anchor corruption reached
                     # a path that used it -- one rotation later.
                     ('T_ZP_PX', 'zp_br_px'), ('T_ZP_PXH', 'zp_br_px_h'),
                     ('T_ZP_PXX', 'zp_br_px_x'),
                     ('T_ZP_PY', 'zp_br_py'), ('T_ZP_PYH', 'zp_br_py_h'),
                     ('T_ZP_PYX', 'zp_br_py_x'),
                     ('T_ZP_VZ', 'zp_br_vz'),
                     ('T_ZP_SMAG', 'zp_br_smag'), ('T_ZP_SNEG', 'zp_br_sneg'),
                     ('T_ZP_SONE', 'zp_br_sone'), ('T_ZP_CMAG', 'zp_br_cmag'),
                     ('T_ZP_CNEG', 'zp_br_cneg'), ('T_ZP_CONE', 'zp_br_cone'),
                     # the rasteriser's line operands, which emit.asm reads
                     ('T_RZP_X0', 'RASTER_ZP_X0'), ('T_RZP_Y0', 'RASTER_ZP_Y0'),
                     ('T_RZP_X1', 'RASTER_ZP_X1'), ('T_RZP_Y1', 'RASTER_ZP_Y1'),
                     ('T_RZP_SCRSTRT', 'RASTER_ZP_SCRSTRT'),
                     # frame-class vectors the driver aims, and the
                     # pre-init clear pointer
                     # BOOT SCRATCH, not engine state (2026-09-04): the copro's
                     # page-copy destination pointer.  It used to borrow
                     # zp_tail_vec; that pair was freed for hot scalars when the
                     # extent cache went, so it borrows the CLIP unit's ox pair
                     # instead -- dead until the engine runs, like zp_save2 (the
                     # source pointer) right above.
                     ('T_ZP_BOOTDST', 'zp_ox0'),
                     ('T_ZP_CLRP', 'zp_save2'),
                     ('T_DRV_SINCOS', 'ROM_DRV_SINCOS_C')):
            f.write(f"{t} = &{fsym(s):04X}\n")
        # THE POINTERS MUST STAY IN ZERO PAGE, AND STAY PAIRED.  tubedrv
        # aims two frame-class vectors and walks its clear loop through
        # (T_ZP_CLRP),Y, all three as lo/hi at addr and addr+1.  A ZP
        # rotation that moved one half, or moved a base out of zero page
        # entirely, would assemble cleanly and produce a wild pointer --
        # so fail the BUILD here instead, where the message is readable.
        for _base, _hi in (('zp_ox0', None),
                           ('zp_save2', 'zp_old_cur')):
            _a = fsym(_base)
            assert _a < 0x100, (
                f'{_base} is at ${_a:04X}: tubedrv dereferences it as a zero '
                f'page pointer, and there is no absolute form of (zp),Y')
            if _hi:
                assert fsym(_hi) == _a + 1, (
                    f'{_base}/{_hi} are no longer adjacent '
                    f'(${_a:04X}/${fsym(_hi):04X}); tubedrv writes the pair')
        # pm_frame's driver-variable contract (abi constants, not map syms).
        # The parasite runs the FLAT build, so take the _FLAT value wherever
        # the symbol forked -- DRV_VARS did, and the DV_* derive from it.
        def _flat(n):
            return getattr(abi, n + '_FLAT', getattr(abi, n))
        for t, v in (('T_DV_ANGIDX', _flat('DV_ANGIDX')), ('T_DV_PXF', _flat('DV_PXF')),
                     ('T_DV_PXL', _flat('DV_PXL')), ('T_DV_PXH', _flat('DV_PXH')),
                     ('T_DV_PYF', _flat('DV_PYF')), ('T_DV_PYL', _flat('DV_PYL')),
                     ('T_DV_PYH', _flat('DV_PYH')),
                     ('T_PM_TURNREM', _flat('PM_TURNREM'))):
            f.write(f"{t} = &{v:04X}\n")
        import colmap as _cm
        f.write(f"T_USEVEC = &{_cm.USEVEC_FLAT:04X}\n")
        # TRIPWIRE lives in src/layout.inc (ca65). Parse it rather than
        # keeping a second copy: the driver AND the host both gate on it,
        # and a drifted copy would silently half-enable the thing.
        import re as _re
        _tw = _re.search(r'^TRIPWIRE\s*=\s*(\d+)',
                         open('src/layout.inc').read(), _re.M)
        _twv = int(_tw.group(1)) if _tw else 0
        f.write(f"T_TRIPWIRE = {_twv}\n")
        if _twv:
            f.write(f"T_TW_CHECK = &{fsym('tw_check'):04X}\n")
            f.write(f"T_ZP_TW = &{fsym('zp_tw'):04X}\n")
        f.write(f"T_VXCACHE_STATE = &{abi.VXCACHE_STATE:04X}\n")
        f.write(f"T_VXCACHE_LEN = &{abi.VXCACHE_STATE_LEN:02X}\n")
        f.write(f"T_VXCACHE_ENABLE = &{abi.VXCACHE_ENABLE:04X}\n")
        f.write(f"T_BCA_AB = &{fsym('bca_ab'):04X}\n")
        f.write(f"SPAWN_ANGIDX = {SPAWN_ANGIDX}\n")
        f.write(f"SPAWN_PXF = &{px88 & 0xFF:02X}\n")
        f.write(f"SPAWN_PXL = &{(px88 >> 8) & 0xFF:02X}\n")
        f.write(f"SPAWN_PXH = &{(px88 >> 16) & 0xFF:02X}\n")
        f.write(f"SPAWN_PYF = &{py88 & 0xFF:02X}\n")
        f.write(f"SPAWN_PYL = &{(py88 >> 8) & 0xFF:02X}\n")
        f.write(f"SPAWN_PYH = &{(py88 >> 16) & 0xFF:02X}\n")
        f.write(f"SPAWN_VZ = &{vz:02X}\n")

def main():
    import pygame; pygame.init()
    import doom_wireframe as dw
    from bsp_render_6502 import BspRender6502
    import symmap, abi
    import build_anim_ssd as anim
    import build_walk_ssd as walkbuild

    # ---- banked (plain Model B) side FIRST, under a clean NMOS env:
    # banked_files() runs the banked build + model images — DOOM_CPU must
    # not be 65c02 yet or the banked engine would silently assemble C02
    # opcodes for the NMOS host.
    walk_files = walkbuild.banked_files()

    # (DOOM_CPU='65c02' is set at MODULE TOP now -- import-time binding.)

    def fsym(name):
        return symmap.sym(name)          # flat build (banked=0 default)

    # ---- full parasite image, exactly the regression harness's memory ----
    r = BspRender6502(dw.packed_layout, dw.packed_rom_main,
                      dw.packed_rom_detail, dw.packed_bbox_table,
                      dw.MAP_CENTER_X, dw.MAP_CENTER_Y, dw.PRESCALE)
    mem = bytearray(r.sc.mpu.memory[0:0x10000])

    # (PLOT PATCHING IS GONE, 2026-09-02 flat-first-class purge: the
    # parasite's plot_h/plot_v/RASTER_ENTRY are EQUATES to the resident
    # glue's emitter slots $F613/$F616/$F610 -- the engine tail-calls
    # the emitters directly.  The model harness plants RTS at those
    # addresses instead; loading COPRES restores the real bodies.)
    for name, slot in (('RASTER_ENTRY', 0x10), ('plot_h', 0x13), ('plot_v', 0x16)):
        assert fsym(name) == RESIDENT + slot, \
            f'{name} is not the glue slot ${RESIDENT+slot:04X} -- tubedrv moved?'

    # ---- anim tables (flat homes $E500/$E600/$E700, inside the DATA
    # span): the harness memory ships WITHOUT them (anim6502_check
    # installs its own copy per run) — before 2026-08-14 the disc shipped
    # zero CFG/TABL0/SSMASK, anim_init configured every mover to
    # min=max=0 and tube anims were frozen.
    import anim_sectors as an
    an.install_6502_tables(mem, flat=True)

    # ---- TWO LOADS (Eben's spec): CODE = engine + NJ/emitters,
    # DATA = level + tables (+anim/sincos). The 2026-07-21 map makes both
    # contiguous; the cache block is runtime-only and never shipped.
    import abi as _abi
    # THE PARASITE LOAD GEOMETRY (2026-09-02, resident re-cut): CODE is
    # everything below the $7800-$7BFF hole (the flat VXCACHE X-plane BSS
    # -- the transient BOOT stub squats it, so neither load may touch it),
    # DATA everything above, INCLUDING the resident glue at $F600-$F7FF.
    CODE_LO, CODE_HI = _abi.LOW_BASE, 0x7800
    GAP_LO,  GAP_HI  = 0x7800, 0x7C00
    DATA_LO, DATA_HI = 0x7C00, 0xF800
    # collision tables + use lines (colmap flat homes = THIS map: the
    # replaced raster pocket + the high-table area)
    import colmap
    colmap.install(mem, flat=True)
    # driver sincos -> the engine's ROM_DRV_SINCOS_C (static $7E00); COPROT
    # reads it there instead of carrying a duplicate sctab (Eben: the only
    # tube-specific code is the ULA driver -- tables are engine data).
    _sc = anim.sincos_table()
    _scb = _abi.ROM_DRV_SINCOS_C_FLAT if hasattr(_abi, 'ROM_DRV_SINCOS_C_FLAT') \
        else fsym('ROM_DRV_SINCOS_C')
    mem[_scb:_scb + len(_sc)] = _sc
    # (COLPORT staging died 2026-08-18: colmap.install put the ports at
    #  $1A00, inside the CODE file span — they ship directly now, and the
    #  sqr quad that took their old $0200 home is boot-generated by
    #  anim_init, which this driver already calls.)
    # PHASE4-PENDING (parasite re-cut 2026-09-02): the copro ships the
    # NEW parasite map (22K + banks laid flat + CBITS) once the tubedrv
    # glue lands (task #34).  Until then the ship checks and the copro
    # files are skipped and the disc carries the HOST modes only.
    # ---- ship guard: nothing nonzero in the COPROT gap (the engine image
    # must leave $7800-$7BFF clear so COPROT can live there) ----
    for a in range(GAP_LO, GAP_HI):
        assert not mem[a], f"engine content in the COPROT gap at &{a:04X}"

    # ---- generated includes: engine syms + spawn, load list ----
    write_tube_syms()
    with open('tube/tube_loads.inc', 'w') as f:
        f.write("\\ GENERATED by tube/build_tube_game.py - DO NOT EDIT.\n")
        f.write('    EQUS "LOAD CODE"\n    EQUB 13\n')
        f.write('    EQUS "LOAD DATA"\n    EQUB 13\n')
        f.write("    EQUB 0\n")

    # ---- assemble the programs ----
    detect = asm('tube/detect.asm', 'DETECT')
    hostt = asm('tube/hostg.asm', 'HOSTT')
    # tubedrv SAVEs TWO blocks: COPROT (transient boot stub, *RUN at
    # $7800) and COPRES (the resident glue+emitters, $F600).  The
    # resident block ships INSIDE the DATA file, so inject it into the
    # image BEFORE the loads are cut.
    subprocess.run([os.path.join(ROOT, 'beebasm'), '-i', 'tube/tubedrv.asm'],
                   cwd=ROOT, check=True)
    coprot = open(os.path.join(ROOT, 'COPROT'), 'rb').read()
    copres = open(os.path.join(ROOT, 'COPRES'), 'rb').read()
    os.remove(os.path.join(ROOT, 'COPROT'))
    os.remove(os.path.join(ROOT, 'COPRES'))
    assert 0xF600 + len(copres) <= 0xF800, 'resident glue reaches the client OS'
    mem[RESIDENT:RESIDENT + len(copres)] = copres
    # ---- STAGE the reclaimed-OS pages (2026-09-02): VEXPL_LO/HI ($F800)
    # and VPTAB ($F900) -- the two documented exceptions to the LINEAR
    # bank-C map -- live above the OS floor, which the copro's *LOADs
    # cannot write (they run through the live client OS).  Ship them
    # STAGED at $7C00-$7DFF (flat VXCACHE Y-plane BSS, zero in the image
    # and dead until the engine runs); the boot stub copies them up after
    # its last OS call.
    assert fsym('VEXPL_LO') == 0xF800, 'stage copy expects VEXPL at $F800'
    import re as _re2
    _vf = _re2.search(r'VPTABF:\s*start = \$F900', open('src/engine_flat.cfg').read())
    assert _vf, 'stage copy expects the VPTABF region at $F900'
    assert not any(mem[0x7C00:0x7E00]), 'stage window not clear at ship time'
    mem[0x7C00:0x7E00] = mem[0xF800:0xFA00]

    # ---- the ONE dual-mode disc (banked side built above) ----
    # PHASE4 LANDED (2026-09-02, resident re-cut): the esend1-misland was
    # the flat VXCACHE X-planes ($7800-$7BFF) writing over emitters that
    # lived in their BSS.  The resident glue moved to $F600-$F7FF (top of
    # memory, inside DATA); only the transient BOOT stub borrows the
    # X-plane hole; VXCACHE is disabled on the copro (its Y-planes map
    # onto VDESC/sincos -- see tubedrv.asm).
    PHASE4 = True
    files = [('!BOOT', 0x30900, 0x30900, detect),
             ('HOSTT', 0x31900, 0x31900, hostt)]
    if PHASE4:
        files += [('COPROT', GAP_LO, GAP_LO, coprot),
                  ('CODE', CODE_LO, CODE_LO, bytes(mem[CODE_LO:CODE_HI])),
                  ('DATA', DATA_LO, DATA_LO, bytes(mem[DATA_LO:DATA_HI]))]
    else:
        print('WARNING: PHASE4-PENDING (emit return sim fault) — disc ships host modes only')
    files += walk_files
    write_ssd(files, os.path.join(ROOT, 'doom_walk.ssd'))


if __name__ == '__main__':
    main()
