#!/usr/bin/env python3
"""Build doom_walk.ssd — THE dual-mode game disc (2026-07-21: the
separate doom_tube.ssd is gone; !BOOT detects a 6502 copro and loads
the Tube version, else chains the banked WALK loader).

The parasite runs the FLAT engine build VERBATIM: this script constructs
the full py65 64K image exactly as the regression harness does
(BspRender6502.__init__: engine link + tables + packed E1M1), then makes
exactly three surgical changes:
  - the NJ rasteriser blob at $A900 is replaced by the Tube emitters
    (tube/emit.asm) — dcl's des_diag JMP $A900 needs no patch at all;
  - plot_h and plot_v entries are poked to JMP $A910/$A920 (the h/v
    emitters). Everything else is byte-identical to the flat build.
The occupied regions are chunked into DFS data files that the copro
bootstrap (tube/tubedrv.asm) *LOADs across the Tube via the parasite OS
before killing the host OS with its raw RUN HOSTT.

Files: !BOOT (tube/detect.asm), COPROT (tubedrv: bootstrap + driver +
tables), HOSTT (tube/hostg.asm: carousel + plot_h/v + real NJ), CODE +
DATA (the two parasite loads), then the banked side from
build_walk_ssd.banked_files() (WALK/BANK0-2/LOW).
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)
os.environ.setdefault('SDL_VIDEODRIVER', 'dummy')
os.environ.setdefault('PYGAME_HIDE_SUPPORT_PROMPT', '1')

SECTOR = 256
TOTAL_SECTORS = 800
SPAWN_X, SPAWN_Y = 1056, -3616
SPAWN_ANGIDX = 16               # angle byte 64, walk_drv's spawn facing
DRIVER_HOME = (0xEA00, 0xF800)  # COPROT in the FB region (engine never writes it)


def write_ssd(files, path):
    disc = bytearray(TOTAL_SECTORS * SECTOR)
    disc[0:8] = b'DOOMTB\x00\x00'
    n = len(files); assert n <= 31, n
    disc[SECTOR + 5] = n * 8
    nxt = 2; secs = []
    for _, _, _, data in files:
        ns = (len(data) + SECTOR - 1) // SECTOR
        secs.append((nxt, ns)); nxt += ns
    total = nxt; assert total <= TOTAL_SECTORS
    disc[SECTOR + 6] = (2 << 4) | ((total >> 8) & 3)
    disc[SECTOR + 7] = total & 0xFF
    for i, (name, load, exe, data) in enumerate(files):
        ss, _ = secs[i]; off = (i + 1) * 8
        disc[off:off+7] = name.encode().ljust(7, b' ')[:7]
        disc[off + 7] = ord('$')
        m = SECTOR + (i + 1) * 8
        disc[m+0] = load & 0xFF; disc[m+1] = (load >> 8) & 0xFF
        disc[m+2] = exe & 0xFF;  disc[m+3] = (exe >> 8) & 0xFF
        disc[m+4] = len(data) & 0xFF; disc[m+5] = (len(data) >> 8) & 0xFF
        disc[m+6] = ((ss>>8)&3) | (((load>>16)&3)<<2) | \
                    (((len(data)>>16)&3)<<4) | (((exe>>16)&3)<<6)
        disc[m+7] = ss & 0xFF
        disc[ss*SECTOR: ss*SECTOR + len(data)] = data
    open(path, 'wb').write(disc)
    print(f"Built {path}: {n} files, {total}/{TOTAL_SECTORS} sectors")
    for i, (name, load, exe, data) in enumerate(files):
        print(f"  {name:7s} &{load:05X}  {len(data):>5} B  sec {secs[i][0]}")


def asm(src, out):
    subprocess.run([os.path.join(ROOT, 'beebasm'), '-i', src],
                   cwd=ROOT, check=True)
    with open(os.path.join(ROOT, out), 'rb') as f:
        data = f.read()
    os.remove(os.path.join(ROOT, out))
    return data


def write_tube_syms():
    """Regenerate tube/tube_syms.inc from the CURRENT engine map (and
    under the CURRENT DOOM_CPU env). The py65 tube tests call this too:
    a stale syms file after any engine-layout slide assembles tubedrv
    against dead addresses (the 2026-08-10 anim_tick crash class)."""
    import doom_wireframe as dw
    import symmap, abi

    def fsym(name):
        return symmap.sym(name)

    px88 = int((SPAWN_X - dw.MAP_CENTER_X) * 256 / dw.PRESCALE) & 0xFFFFFF
    py88 = int((SPAWN_Y - dw.MAP_CENTER_Y) * 256 / dw.PRESCALE) & 0xFFFFFF
    vz = dw._prescale_height(dw.player_floor(SPAWN_X, SPAWN_Y) + 41) & 0xFF
    with open('tube/tube_syms.inc', 'w') as f:
        f.write("\\ GENERATED by tube/build_tube_game.py - DO NOT EDIT.\n")
        for t, s in (('T_VIEW_SETUP', 'view_setup'),
                     ('T_SPAN_INIT', 'span_init'),
                     ('T_RENDER_FRAME', 'render_frame'),
                     ('T_TAIL_POSTRC', 'bca_tail_postrc'),
                     ('T_BOX_CLASSIFY', 'box_classify'),
                     ('T_ANIM_INIT', 'anim_init'),
                     ('T_ANIM_TICK', 'anim_tick'),
                     ('T_ANIM_ENABLE', 'ANIM_ENABLE'),
                     ('T_D_ENABLE', 'D_ENABLE'),
                     ('T_D_FWD', 'D_FWD'),
                     ('T_CPM_KDXH', 'CPM_KDXH'),
                     # PMOVE: the parasite runs the SAME DOOM collision /
                     # slide / frame-rate-compensated walk as walk_drv
                     # (2026-08-23).  pm_frame owns rotation, position,
                     # slide and D_FWD; pmove_zonly re-derives z so the
                     # copro rides live lifts too.
                     ('T_PM_FRAME', 'pm_frame'),
                     ('T_PMOVE_ZONLY', 'pmove_zonly'),
                     ('T_PM_VZ', 'pm_vz'),
                     # SPACE 'use': without it every DR door on the map is
                     # shut forever (anim_sectors: "shut until used"), which
                     # is not a rendering bug but a missing input path.
                     ('T_PMOVE_USE', 'pmove_use'),
                     ('T_PM_UX', 'pm_ux')):
            f.write(f"{t} = &{fsym(s):04X}\n")
        # pm_frame's driver-variable contract (abi constants, not map syms)
        for t, v in (('T_DV_ANGIDX', abi.DV_ANGIDX), ('T_DV_PXF', abi.DV_PXF),
                     ('T_DV_PXL', abi.DV_PXL), ('T_DV_PXH', abi.DV_PXH),
                     ('T_DV_PYF', abi.DV_PYF), ('T_DV_PYL', abi.DV_PYL),
                     ('T_DV_PYH', abi.DV_PYH),
                     ('T_PM_TURNREM', abi.PM_TURNREM)):
            f.write(f"{t} = &{v:04X}\n")
        f.write(f"T_RCACHE_STATE = &{abi.RCACHE_STATE_FLAT:04X}\n")
        import colmap as _cm
        f.write(f"T_USEVEC = &{_cm.USEVEC_FLAT:04X}\n")
        f.write(f"T_RCACHE_LEN = &{abi.RCACHE_STATE_LEN & 0xFF:02X}\n")
        f.write(f"T_VXC_STATE = &{abi.VXC_STATE:04X}\n")
        f.write(f"T_VXC_LEN = &{abi.VXC_STATE_LEN:02X}\n")
        f.write(f"T_VXC_ENABLE = &{abi.VXC_ENABLE:04X}\n")
        f.write(f"T_BCA_AB = &{fsym('bca_ab'):04X}\n")
        f.write(f"SPAWN_ANGIDX = {SPAWN_ANGIDX}\n")
        f.write(f"SPAWN_PXF = &{px88 & 0xFF:02X}\n")
        f.write(f"SPAWN_PXL = &{(px88 >> 8) & 0xFF:02X}\n")
        f.write(f"SPAWN_PXH = &{(px88 >> 16) & 0xFF:02X}\n")
        f.write(f"SPAWN_PYF = &{py88 & 0xFF:02X}\n")
        f.write(f"SPAWN_PYL = &{(py88 >> 8) & 0xFF:02X}\n")
        f.write(f"SPAWN_PYH = &{(py88 >> 16) & 0xFF:02X}\n")
        f.write(f"SPAWN_VZ = &{vz:02X}\n")

def main():
    import pygame; pygame.init()
    import doom_wireframe as dw
    from bsp_render_6502 import BspRender6502
    import symmap, abi
    import build_anim_ssd as anim
    import build_walk_ssd as walkbuild

    # ---- banked (plain Model B) side FIRST, under a clean NMOS env:
    # banked_files() runs the banked build + model images — DOOM_CPU must
    # not be 65c02 yet or the banked engine would silently assemble C02
    # opcodes for the NMOS host.
    walk_files = walkbuild.banked_files()

    os.environ['DOOM_CPU'] = '65c02'    # NOW the copro side: it IS a 65C02
                                        # (3MHz) — the parasite engine
                                        # assembles with C02=1 (STZ/BRA/
                                        # ZERO sites live). Host stays NMOS.

    def fsym(name):
        return symmap.sym(name)          # flat build (banked=0 default)

    # ---- full parasite image, exactly the regression harness's memory ----
    r = BspRender6502(dw.packed_layout, dw.packed_rom_main,
                      dw.packed_rom_detail, dw.packed_bbox_table,
                      dw.MAP_CENTER_X, dw.MAP_CENTER_Y, dw.PRESCALE)
    mem = bytearray(r.sc.mpu.memory[0:0x10000])

    # ---- the three surgical changes ----
    emit = asm('tube/emit.asm', 'EMIT')
    # drop the OR blob (flat RASTER_ENTRY = $7500 since the 2026-08-09
    # cache-region map; $6200-$6B00 is LIVE CLIPF now — the old window
    # was the pre-shuffle blob home and zeroing it was the black-screen)
    mem[0x7500:0x7E00] = bytes(0x7E00 - 0x7500)
    mem[0x7500:0x7500 + len(emit)] = emit
    for name, target in (('plot_h', 0x7510), ('plot_v', 0x7520)):
        a = fsym(name)
        mem[a] = 0x4C
        mem[a+1] = target & 0xFF
        mem[a+2] = target >> 8
        print(f"  poked {name} @ &{a:04X} -> JMP &{target:04X}")

    # ---- anim tables (flat homes $E500/$E600/$E700, inside the DATA
    # span): the harness memory ships WITHOUT them (anim6502_check
    # installs its own copy per run) — before 2026-08-14 the disc shipped
    # zero CFG/TABL0/SSMASK, anim_init configured every mover to
    # min=max=0 and tube anims were frozen.
    import anim_sectors as an
    an.install_6502_tables(mem, flat=True)

    # ---- TWO LOADS (Eben's spec): CODE = engine + NJ/emitters,
    # DATA = level + tables (+anim/sincos). The 2026-07-21 map makes both
    # contiguous; the cache block is runtime-only and never shipped.
    import abi as _abi
    CODE_LO, CODE_HI = _abi.LOW_BASE, 0x8600   # strip head (window slide 2026-08-19);
                                        # CLIPF ends ~$6D65, VPLOTF $6E00,
                                        # emit at $7500, collision tables
                                        # $7600-$7DF2, engine PMOVE $7E00,
                                        # CPM (boot-init) $2900 — one file
    DATA_LO, DATA_HI = 0x8600, 0xEA00
    # collision tables + use lines (colmap flat homes = THIS map: the
    # replaced raster pocket + the high-table area)
    import colmap
    colmap.install(mem, flat=True)
    # (COLPORT staging died 2026-08-18: colmap.install put the ports at
    #  $1A00, inside the CODE file span — they ship directly now, and the
    #  sqr quad that took their old $0200 home is boot-generated by
    #  anim_init, which this driver already calls.)
    # guard: nothing nonzero outside the shipped spans + runtime regions
    # ($0400-$1A00 = pool/records/caches ground state; $8400-$8600 =
    # CPM-era slack, boot-initialized)
    for a in range(0x0400, 0xF7F0):
        if mem[a] and not (CODE_LO <= a < CODE_HI or DATA_LO <= a < DATA_HI
                           or 0x0400 <= a < CODE_LO or 0x7600 <= a < 0x8600):
            raise AssertionError(f"unshipped nonzero byte at &{a:04X}")
    # (high check: VATOX now ends at $E701 — nothing above $E9FF but FB)
    for a in range(0xEA00, 0xF7F0):
        assert not mem[a], f"nonzero in FB region &{a:04X}"

    runs = []                              # (census retired: two spans)

    # ---- generated includes: engine syms + spawn, load list ----
    write_tube_syms()

    with open('tube/tube_loads.inc', 'w') as f:
        f.write("\\ GENERATED by tube/build_tube_game.py - DO NOT EDIT.\n")
        f.write('    EQUS "LOAD CODE"\n    EQUB 13\n')
        f.write('    EQUS "LOAD DATA"\n    EQUB 13\n')
        f.write("    EQUB 0\n")

    # ---- driver tables ----
    open('SINCOS.bin', 'wb').write(anim.sincos_table())
    walkbuild.build_floor_grid()            # writes FLOORGRD.bin

    # ---- assemble the three programs ----
    detect = asm('tube/detect.asm', 'DETECT')
    coprot = asm('tube/tubedrv.asm', 'COPROT')
    hostt = asm('tube/hostg.asm', 'HOSTT')

    # ---- assemble the ONE dual-mode disc (banked side built above) ----
    files = [('!BOOT', 0x30900, 0x30900, detect),
             ('COPROT', 0x0EA00, 0x0EA00, coprot),
             ('HOSTT', 0x31900, 0x31900, hostt),
             ('CODE', CODE_LO, CODE_LO, bytes(mem[CODE_LO:CODE_HI])),
             ('DATA', DATA_LO, DATA_LO, bytes(mem[DATA_LO:DATA_HI]))]
    files += walk_files
    write_ssd(files, os.path.join(ROOT, 'doom_walk.ssd'))


if __name__ == '__main__':
    main()
