
; ============================================================================
; Animated sectors (doors / lifts) — 6502 runtime.
;
; Mirrors the python prototype's two-level design (anim_sectors.py):
;   LOGICAL heights advance every frame in anim_tick (per-mover state
;   machine over a 3-byte block: pos 8.8 prescaled + packed state/timer).
;   APPLIED heights (the bytes the renderer reads) update lazily: the
;   br_render_subsector hook (anim_ss_hook, SMC like the vxc/bca hooks)
;   consults a per-subsector mover bitmask and patches a dirty mover the
;   first time a frame visits any subsector containing one of its segs.
;   An invisible mover's stale bytes are never read, so lazy == eager.
;
; A patch writes, per mover (table-driven; tables generated at pack time
; by anim_sectors.gen_6502_tables and poked by the harness/disc build):
;   header HEIGHT bytes — n_fhch u16 addrs into the 16-byte seg headers
;     (+10..15; the separate FHCH stream was retired 2026-07-11 — the
;     'fhch' naming in the tables survives as history), value = pos_hi
;   seg-header FLAG bytes — SOLID/NEEDBT/NEEDBB re-derived from the
;     (patched) height quad
; Both live in bank L0 banked / $6C00 flat, so the workers run paged.
;
; Segments (ALL code in the one CODE region banked; flat: ANIMH+ANIML0
; in the ACOLD island $E740, ANIML2 in CODE — see engine_flat.cfg):
; ANIMH = resident hub (pages banks, walks dirty&visible bits);
; ANIML0 = header height+flags patch worker (runs with BANK_L0 paged);
; ANIML2 = tick + init (runs with BANK_L2 paged: the CFG table lives in
; the L2 window at $BA00).
; ============================================================================

; --- table/data addresses (contents generated by anim_sectors.py) ---
.if ::BANKED
ANIM_SSMASK = $0A80                     ; MAIN: u8 mover bitmask per subsector
                                        ; (rule exception: read per subsector
                                        ; under any bank; main = zero paging)
ANIM_TABL0  = $BE90                     ; L0: 6 u16 ptrs -> per-mover blocks
ANIM_CFG    = $BA00                     ; L2: 12 B per mover (bounds/speed/waits)
ANIM_SSMASK_SRC = $BB00                 ; L2: staging page for SSMASK — the
                                        ; disc can only ship bank contents
                                        ; (LOW loads at $1B40), so anim_init
                                        ; copies this page down to $0A80
.else
ANIM_SSMASK = $E484
ANIM_TABL0  = $E580
ANIM_CFG    = $E680
.endif
; CFG record layout (12 B/mover, anim_sectors.gen_6502_tables; heights are
; prescaled 8.8 fixed point — hi byte = the packer's prescaled s8 height):
;   +0  min88  (s16: endpoint "A" — doors: closed, lifts: bottom)
;   +2  max88  (s16: endpoint "B" — doors: open,   lifts: top)
;   +4  speed88 (u16, per frame)
;   +6  wait_at_A, +7 wait_at_B (frames, <= 63 to fit the packed timer)
;   +8  start88, +10 packed start state/timer, +11 pad
; Mover bit/index m = index in sorted(ANIM_SECTORS) everywhere (SSMASK bits,
; TABL0 pointer slots, CFG stride 12, ANIM_WS stride 3, DIRTY bits).

; --- state (unbanked; drivers zero $05E9-$05FF at init) ---
ANIM_ENABLE = $05E9
ANIM_DIRTY  = $05EA                     ; bit m set = mover m moved since patch
ANIM_WS     = $05EB                     ; per mover: pos_lo, pos_hi, state/timer
                                        ;   state = bits 7-6 (0 wait@A, 1 A->B,
                                        ;   2 wait@B, 3 B->A), timer = bits 5-0

; --- zp scratch (frame-scoped; free per zpcheck) ---
; (zp_anim_p/zp_anim_w/ANIM_VAL/ANIM_CUR moved to zp.inc 2026-07-10 —
; registered at $5D/$5F/$27/$29; they were unregistered squatters at
; $EB-$EE/$F0/$F1, which now belong to the free top block.)

; ============================================================================
; Resident hub — anim_ss_hook (in subsector.s) is SMC-patched here by
; anim_init. Entry: BANK_L0 paged, subsector index (u8) at zp_node_ch_l.
; A/X/Y are dead at the hook point (br_render_subsector reloads them).
; ============================================================================
.if ::BANKED
.segment "ANIMH"
.else
.segment "ANIMH"
.endif

; pseudocode:
;   pend = SSMASK[ss] & DIRTY            # dirty movers revealable via this ss
;   for m in 5..0 where pend has bit m:
;     ANIM_VAL = pos_hi(m)               # ANIM_WS[m*3+1], prescaled s8 height
;     anim_l0_worker (FHCH bytes + seg flags)
;     DIRTY &= ~bit(m)                   # applied == logical again
anim_hub:
.scope
   LDX zp_node_ch_l
   LDA ANIM_SSMASK,X                       ; movers with segs in this subsector
   AND ANIM_DIRTY
   BEQ ah_done
   STA ah_pend
   LDX #5
ah_loop:
   LDA ah_pend
   AND ah_bit,X
   BEQ ah_next
   STX ANIM_CUR
; value = pos_hi of mover X (ws + X*3 + 1)
   TXA
   ASL A
   ADC ANIM_CUR                            ; A = X*3 (carry clear: X<=5)
   TAY
   LDA ANIM_WS+1,Y
   STA ANIM_VAL
   JSR anim_l0_worker                      ; FHCH bytes + seg flags (L0 paged)
; (the L2 VWH worker is gone: the private VWH slot bytes were write-only —
; the 6502 render projects from the header height bytes; VWH indices are Python-side
; cache keys. Stripped 2026-07-10.)
   LDX ANIM_CUR
   LDA ANIM_DIRTY
   EOR ah_bit,X                            ; clear this mover's dirty bit
   STA ANIM_DIRTY
ah_next:
   DEX
   BPL ah_loop
ah_done:
   JMP anim_ss_cont                        ; resume br_render_subsector
ah_bit:
   .byte 1,2,4,8,16,32
ah_pend:
   .byte 0
.endscope

; ============================================================================
; BANK_L0-context code: jump table (fixed entry addrs for the driver),
; per-frame tick, init, and the FHCH+flags patch worker.
; ============================================================================
.segment "ANIML2"

; (jt_anim_tick/jt_anim_init moved into the pinned MAIN jump table at
;  $2C1E/$2C21 — see bsp/header.s; the one-region merge lets ANIML2 float.)

; --- anim_tick: advance every mover's logical state; no table writes.
;     Per mover: Y = m*3 indexes the WS block, X = m*12 the CFG block.
;     Prescaled 8.8 arithmetic; bounds |int| <= ~30 so SBC-sign compares
;     are exact. Sets the mover's ANIM_DIRTY bit iff pos_hi changed. ---
; pseudocode (integerised Mover.tick, anim_sectors.py):
;   for m in 5..0:
;     state = WS[m*3+2] & $C0 ; timer = WS[m*3+2] & $3F
;     if state in (0 wait@A, 2 wait@B):
;       if --timer == 0: state += $40      # 0 -> 1 (A->B), 2 -> 3 (B->A)
;     elif state == 1 (A->B):
;       pos += speed88; if pos >= max88: pos = max88; state = 2; timer = wait_B
;     else (3, B->A):
;       pos -= speed88; if pos < min88:  pos = min88; state = 0; timer = wait_A
;     WS[m*3+2] = state | timer
;     if pos_hi != previous pos_hi: DIRTY |= bit(m)  # renderer bytes now stale
anim_tick:
.scope
   LDA ANIM_ENABLE
   BNE at_on
   RTS
at_on:
   LDA #5
   STA at_m
at_loop:
   LDA at_m
   ASL A
   ADC at_m                                ; m*3 (no carry: m<=5)
   TAY
   LDA at_m
   ASL A
   ASL A
   STA at_t                                ; m*4
   ASL A                                   ; m*8
   CLC
   ADC at_t                                ; m*12
   TAX
   LDA ANIM_WS+1,Y
   STA at_prevhi
   LDA ANIM_WS+2,Y
   AND #$3F
   STA at_timer
   LDA ANIM_WS+2,Y
   AND #$C0
   STA at_state
   BNE at_notwa
   JMP at_wait                             ; 0: wait at A
at_notwa:
   CMP #$80
   BNE at_notwb
   JMP at_wait                             ; 2: wait at B
at_notwb:
   CMP #$40
   BEQ at_up                               ; 1: A -> B
; --- 3: B -> A (pos -= speed, clamp at min = CFG+0) ---
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+4,X
   STA ANIM_WS+0,Y
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+5,X
   STA ANIM_WS+1,Y
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+0,X
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+1,X
   BPL at_done                             ; pos >= min: still travelling
   LDA ANIM_CFG+0,X
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+1,X
   STA ANIM_WS+1,Y
   LDA #$00
   STA at_state
   LDA ANIM_CFG+6,X                        ; wait_at_A
   STA at_timer
   JMP at_done

at_up:
; --- 1: A -> B (pos += speed, clamp at max = CFG+2) ---
   LDA ANIM_WS+0,Y
   CLC
   ADC ANIM_CFG+4,X
   STA ANIM_WS+0,Y
   LDA ANIM_WS+1,Y
   ADC ANIM_CFG+5,X
   STA ANIM_WS+1,Y
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+2,X
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+3,X
   BMI at_done                             ; pos < max: still travelling
   LDA ANIM_CFG+2,X
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+3,X
   STA ANIM_WS+1,Y
   LDA #$80
   STA at_state
   LDA ANIM_CFG+7,X                        ; wait_at_B
   STA at_timer
   JMP at_done

at_wait:
   DEC at_timer
   BNE at_done
; wait expired: 0 -> 1 (A->B), 2 -> 3 (B->A); timer stays 0 while moving
   LDA at_state
   CLC
   ADC #$40
   STA at_state
   LDA #0
   STA at_timer

at_done:
   LDA at_state
   ORA at_timer
   STA ANIM_WS+2,Y
   LDA ANIM_WS+1,Y
   CMP at_prevhi
   BEQ at_clean
   LDX at_m
   LDA ANIM_DIRTY
   ORA anim_bit2,X
   STA ANIM_DIRTY
at_clean:
   DEC at_m
   BMI at_end
   JMP at_loop
at_end:
   RTS
at_m:      .byte 0
at_t:      .byte 0
at_state:  .byte 0
at_timer:  .byte 0
at_prevhi: .byte 0
.endscope

anim_bit2:
   .byte 1,2,4,8,16,32

; --- anim_l0_worker: patch FHCH bytes + re-derive seg flags for mover
;     ANIM_CUR with value ANIM_VAL. Runs with BANK_L0 paged. ---
; TABL0 block (gen_6502_tables): n_fhch, n_flag, then n_fhch u16 FHCH byte
; addresses (the MOVING role only — doors: ch/bch slots, lifts: fh/bfh),
; then n_flag x (u16 seg-header flag addr, u16 FHCH quad addr) covering
; every two-sided seg touching the sector.
; pseudocode:
;   for each fhch addr: *addr = ANIM_VAL
;   for each flag entry:                       # packer's rules, post-patch
;     fh,ch,bfh,bch = quad[0..3]               # prescaled s8, SBC sign exact
;     f = *hdr & ~(SOLID|NEEDBT|NEEDBB)        # & $F1
;     if bch <= fh or bfh >= ch: f |= SOLID
;     else: if bch < ch: f |= NEEDBT ; if bfh > fh: f |= NEEDBB
;     *hdr = f
.segment "ANIML0"
anim_l0_worker:
.scope
   LDA ANIM_CUR
   ASL A
   TAY
   LDA ANIM_TABL0,Y
   STA zp_anim_p
   LDA ANIM_TABL0+1,Y
   STA zp_anim_p+1
   LDY #0
   LDA (zp_anim_p),Y                       ; n_fhch
   STA alw_nf
   INY
   LDA (zp_anim_p),Y                       ; n_flag
   STA alw_ng
   INY
; FHCH byte patches
alw_floop:
   LDA alw_nf
   BNE alw_fbody
   JMP alw_flags
alw_fbody:
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
   LDY #0
   LDA ANIM_VAL
   STA (zp_anim_w),Y
   LDY alw_y
   DEC alw_nf
   JMP alw_floop
alw_flags:
; per flag entry: u16 hdr flag addr, u16 FHCH quad addr
   LDA alw_ng
   BNE alw_gbody
   JMP alw_done
alw_gbody:
   LDA (zp_anim_p),Y
   STA alw_hdr
   INY
   LDA (zp_anim_p),Y
   STA alw_hdr+1
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
; read quad: fh, ch, bfh, bch (prescaled s8; |h| small so SBC sign is exact)
   LDY #0
   LDA (zp_anim_w),Y
   STA alw_fh
   INY
   LDA (zp_anim_w),Y
   STA alw_ch
   INY
   LDA (zp_anim_w),Y
   STA alw_bfh
   INY
   LDA (zp_anim_w),Y
   STA alw_bch
; flags = old & ~(SOLID|NEEDBT|NEEDBB) = old & ~$0E
   LDA alw_hdr
   STA zp_anim_w
   LDA alw_hdr+1
   STA zp_anim_w+1
   LDY #0
   LDA (zp_anim_w),Y
   AND #$F1
   STA alw_f
; SOLID iff bch <= fh  or  bfh >= ch
   LDA alw_bch
   SEC
   SBC alw_fh
   BMI alw_solid
   BEQ alw_solid
   LDA alw_bfh
   SEC
   SBC alw_ch
   BPL alw_solid
; portal: NEEDBT iff bch < ch ; NEEDBB iff bfh > fh
   LDA alw_bch
   SEC
   SBC alw_ch
   BPL alw_nobt
   LDA alw_f
   ORA #$04                                ; SF_NEEDBT
   STA alw_f
alw_nobt:
   LDA alw_fh
   SEC
   SBC alw_bfh
   BPL alw_nobb
   LDA alw_f
   ORA #$08                                ; SF_NEEDBB
   STA alw_f
alw_nobb:
   JMP alw_wf
alw_solid:
   LDA alw_f
   ORA #$02                                ; SF_SOLID
   STA alw_f
alw_wf:
   LDA alw_f
   STA (zp_anim_w),Y
   LDY alw_y
   DEC alw_ng
   JMP alw_flags
alw_done:
   RTS
alw_nf:  .byte 0
alw_ng:  .byte 0
alw_y:   .byte 0
alw_hdr: .word 0
alw_fh:  .byte 0
alw_ch:  .byte 0
alw_bfh: .byte 0
alw_bch: .byte 0
alw_f:   .byte 0
.endscope

; --- anim_init: load start state from CFG, mark all dirty, enable, and
;     point the subsector hook at the hub. Runs with BANK_L2 paged. ---
;   in : ANIM_CFG (+8 start88, +10 packed start state/timer)
;   out: ANIM_WS seeded (all 6 movers), ANIM_DIRTY = $3F (every mover patches
;        on first visibility, even before any motion), ANIM_ENABLE = 1,
;        anim_ss_hook operand SMC-patched -> anim_hub, ANIM_SSMASK copied
;        down from its L2 staging page (banked only — see below).
.segment "ANIML2"
anim_init:
.scope
.if ::BANKED
; SSMASK lives in MAIN ($0A80) so the hub can read it under any bank —
; but main RAM below $1B40 is NOT covered by the disc's LOW image, so
; the mask must ship inside a bank and be copied down here (L2 is
; paged). The 355c126 reshuffle moved it to $0A80 without this copy:
; the model harness pokes main RAM directly, so every banked gate
; passed while the DISC ran against OS boot junk and doors froze
; (found 2026-07-17 — anim coverage is flat-only, jsbeeb is the catcher).
   LDX #0
ai_cp:
   LDA ANIM_SSMASK_SRC,X
   STA ANIM_SSMASK,X
   INX
   BNE ai_cp                               ; 256 bytes (staged page is padded)
.endif
   LDA #5
   STA ai_midx
ai_m:
   LDA ai_midx
   ASL A
   CLC
   ADC ai_midx
   TAY                                     ; m*3
   LDA ai_midx
   ASL A
   ASL A
   STA ai_t                                ; m*4
   ASL A                                   ; m*8
   CLC
   ADC ai_t                                ; m*12
   TAX
   LDA ANIM_CFG+8,X                        ; start pos (8.8 prescaled)
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+9,X
   STA ANIM_WS+1,Y
   LDA ANIM_CFG+10,X                       ; packed start state/timer
   STA ANIM_WS+2,Y
   DEC ai_midx
   BPL ai_m
   LDA #$3F
   STA ANIM_DIRTY
   LDA #1
   STA ANIM_ENABLE
   LDA #<anim_hub
   STA anim_ss_hook+1
   LDA #>anim_hub
   STA anim_ss_hook+2
   RTS
ai_t:    .byte 0
ai_midx: .byte 0
.endscope


.segment "MAIN"
