
; ============================================================================
; Animated sectors (doors / lifts) — 6502 runtime.
;
; Mirrors the python prototype's two-level design (anim_sectors.py):
;   LOGICAL heights advance every frame in anim_tick (per-mover state
;   machine over a 3-byte block: pos 8.8 prescaled + packed state/timer).
;   APPLIED heights (the bytes the renderer reads) update lazily: the
;   render_subsector hook (anim_ss_hook, SMC like the vxc/bca hooks)
;   consults a per-subsector mover bitmask and patches a dirty mover the
;   first time a frame visits any subsector containing one of its segs.
;   An invisible mover's stale bytes are never read, so lazy == eager.
;
; A patch writes, per mover (table-driven; tables generated at pack time
; by anim_sectors.gen_6502_tables and poked by the harness/disc build):
;   HEIGHT bytes — n_fhch u16 addrs: the per-subsector front-height pages
;     for the mover's own sector, the seg headers' +10/+11 back pair for
;     segs facing it (the separate FHCH stream was retired 2026-07-11 — the
;     'fhch' naming in the tables survives as history), value = pos_hi
;   seg-header FLAG bytes — SOLID/NEEDBT/NEEDBB re-derived from the
;     (patched) height quad
; Both live in bank L0 banked / $6C00 flat, so the workers run paged.
;
; Segments (ALL code in the one CODE region banked; flat: ANIMH+ANIML0
; in the ACOLD island $E740, ANIML2 in CODE — see engine_flat.cfg):
; ANIMH = resident hub (pages banks, walks dirty&visible bits);
; ANIML0 = header height+flags patch worker (runs with BANK_L0 paged);
; ANIML2 = tick + init (runs with BANK_L2 paged: the CFG table lives in
; the L2 window at $BA00).
; ============================================================================

; --- table/data addresses (contents generated by anim_sectors.py) ---
; ANIM_SSMASK is the SIXTH per-subsector plane (Eben, 2026-08-19): the
; hub is entered WALK-paged (see the subsector prologue), so the banked
; mask reads IN PLACE from the bank-B page the disc ships — the old
; $1100 main copy and anim_init's page copy-down are DELETED, and $1100
; is free in BOTH builds (flat reads its own shipped page too).
.if ::BANKED
ANIM_TABL0  = $BE90                     ; L0: 6 u16 ptrs -> per-mover blocks
ANIM_CFG    = $B300                     ; L2: 12 B per mover (bounds/speed/waits)
ANIM_SSMASK = $B400                     ; L2 (=WALK): read by the hub under
                                        ; the bank it already holds — zero
                                        ; paging, and the $B4DD-$B4FF tail
                                        ; is genuinely free now (no page
                                        ; copy drags it anywhere)
.else
ANIM_TABL0  = $E600
ANIM_CFG    = $E700
ANIM_SSMASK = $E500                     ; flat TABLES block page (shipped in
                                        ; the copro DATA file) — the flat
                                        ; runtime home again, as pre-unfork
.endif
; CFG record layout (12 B/mover, anim_sectors.gen_6502_tables; heights are
; prescaled 8.8 fixed point — hi byte = the packer's prescaled s8 height):
;   +0  min88  (s16: endpoint "A" — doors: closed, lifts: bottom)
;   +2  max88  (s16: endpoint "B" — doors: open,   lifts: top)
;   +4  speed88 (u16, per frame)
;   +6  wait_at_A, +7 wait_at_B (frames, <= 63 to fit the packed timer)
;   +8  start88, +10 packed start state/timer, +11 pad
; Mover bit/index m = index in sorted(ANIM_SECTORS) everywhere (SSMASK bits,
; TABL0 pointer slots, CFG stride 12, ANIM_WS stride 3, DIRTY bits).

; --- state (unbanked; ships as LOW zeros, anim_init seeds it) ---
ANIM_ENABLE = $19E9                     ; scalars block: $05xx -> $1Dxx (sqr
ANIM_DIRTY  = $19EA                     ; swap) -> $19xx (2026-08-19 window
ANIM_WS     = $19EB                     ; slide); same page offsets.
                                        ; per mover: pos_lo, pos_hi, state/timer
                                        ;   state = bits 7-6 (0 wait@A, 1 A->B,
                                        ;   2 wait@B, 3 B->A), timer = bits 5-0

; --- zp scratch (frame-scoped; free per zpcheck) ---
; (zp_anim_p/zp_anim_w/ANIM_VAL/ANIM_CUR moved to zp.inc 2026-07-10 —
; registered at $5D/$5F/$27/$29; they were unregistered squatters at
; $EB-$EE/$F0/$F1, which now belong to the free top block.)

; ============================================================================
; Resident hub — anim_ss_hook (in subsector.s) is SMC-patched here by
; anim_init. Entry: bank WALK paged (the hook moved to the FRONT of the
; prologue 2026-08-19, before any SS read); the no-work exit leaves the
; bank untouched, the work path restores WALK after the workers.
; A/X/Y are dead at the hook point (render_subsector reloads them).
; ============================================================================
SEG_HIGH
; pseudocode:
;   pend = SSMASK[ss] & DIRTY            # dirty movers revealable via this ss
;   for m in 5..0 where pend has bit m:
;     ANIM_VAL = pos_hi(m)               # ANIM_WS[m*3+1], prescaled s8 height
;     anim_l0_worker (FHCH bytes + seg flags)
;     DIRTY &= ~bit(m)                   # applied == logical again
anim_hub:
.scope
   LDX zp_node_ch_l
   LDA ANIM_SSMASK,X                       ; movers with segs in this subsector
   AND ANIM_DIRTY
   BEQ ah_done
   STA ah_pend
   LDX #5
ah_loop:
   LDA ah_pend
   AND ah_bit,X
   BEQ ah_next
   STX ANIM_CUR
; value = pos_hi of mover X (ws + X*3 + 1)
   TXA
   ASL A
   ADC ANIM_CUR                            ; A = X*3 (carry clear: X<=5)
   TAY
   LDA ANIM_WS+1,Y
   STA ANIM_VAL
   JSR anim_l0_worker                      ; heights + seg flags (pages itself)
; (the L2 VWH worker is gone: the private VWH slot bytes were write-only —
; the 6502 render projects from the header height bytes; VWH indices are Python-side
; cache keys. Stripped 2026-07-10.)
   LDX ANIM_CUR
   LDA ANIM_DIRTY
   EOR ah_bit,X                            ; clear this mover's dirty bit
   STA ANIM_DIRTY
ah_next:
   DEX
   BPL ah_loop
   PAGE BANK_WALK                          ; the workers left SEG paged; the
                                        ; prologue's SS reads need WALK back
ah_done:
   JMP anim_ss_cont                        ; resume render_subsector
ah_bit:
   .byte 1,2,4,8,16,32
ah_pend:
   .byte 0
.endscope

; ============================================================================
; BANK_L0-context code: jump table (fixed entry addrs for the driver),
; per-frame tick, init, and the FHCH+flags patch worker.
; ============================================================================
SEG_HIGH

; (jt_anim_tick/jt_anim_init moved into the pinned MAIN jump table at
;  $2C1E/$2C21 — see bsp/header.s; the one-region merge lets ANIML2 float.)

; --- anim_tick: advance every mover's logical state; no table writes.
;     Per mover: Y = m*3 indexes the WS block, X = m*12 the CFG block.
;     Prescaled 8.8 arithmetic; bounds |int| <= ~30 so SBC-sign compares
;     are exact. Sets the mover's ANIM_DIRTY bit iff pos_hi changed. ---
; pseudocode (integerised Mover.tick, anim_sectors.py):
;   for m in 5..0:
;     state = WS[m*3+2] & $C0 ; timer = WS[m*3+2] & $3F
;     if state in (0 wait@A, 2 wait@B):
;       if --timer == 0: state += $40      # 0 -> 1 (A->B), 2 -> 3 (B->A)
;     elif state == 1 (A->B):
;       pos += speed88; if pos >= max88: pos = max88; state = 2; timer = wait_B
;     else (3, B->A):
;       pos -= speed88; if pos < min88:  pos = min88; state = 0; timer = wait_A
;     WS[m*3+2] = state | timer
;     if pos_hi != previous pos_hi: DIRTY |= bit(m)  # renderer bytes now stale
anim_tick:
.scope
   LDA ANIM_ENABLE
   BNE at_on
   RTS
at_on:
   LDA #5
   STA at_m
at_loop:
   LDA at_m
   ASL A
   ADC at_m                                ; m*3 (no carry: m<=5)
   TAY
   LDA at_m
   ASL A
   ASL A
   STA at_t                                ; m*4
   ASL A                                   ; m*8
   CLC
   ADC at_t                                ; m*12
   TAX
   LDA ANIM_WS+1,Y
   STA at_prevhi
   LDA ANIM_WS+2,Y
   AND #$3F
   STA at_timer
   LDA ANIM_WS+2,Y
   AND #$C0
   STA at_state
   BNE at_notwa
   JMP at_wait                             ; 0: wait at A
at_notwa:
   CMP #$80
   BNE at_notwb
   JMP at_wait                             ; 2: wait at B
at_notwb:
   CMP #$40
   BEQ at_up                               ; 1: A -> B
; --- 3: B -> A (pos -= speed, clamp at min = CFG+0) ---
   ZERO D_FWD                              ; geometry moves THIS frame:
                                        ; forward-coherence bbox serves
                                        ; would inherit stale occlusion
                                        ; (D + anims gate, 2026-08-13)
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+4,X
   STA ANIM_WS+0,Y
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+5,X
   STA ANIM_WS+1,Y
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+0,X
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+1,X
   BPL at_done                             ; pos >= min: still travelling
   LDA ANIM_CFG+0,X
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+1,X
   STA ANIM_WS+1,Y
   ZERO at_state
   LDA ANIM_CFG+6,X                        ; wait_at_A
   STA at_timer
   JMP at_done

at_up:
; --- 1: A -> B (pos += speed, clamp at max = CFG+2) ---
   ZERO D_FWD                              ; (mirror of the B->A gate)
   LDA ANIM_WS+0,Y
   CLC
   ADC ANIM_CFG+4,X
   STA ANIM_WS+0,Y
   LDA ANIM_WS+1,Y
   ADC ANIM_CFG+5,X
   STA ANIM_WS+1,Y
   LDA ANIM_WS+0,Y
   SEC
   SBC ANIM_CFG+2,X
   LDA ANIM_WS+1,Y
   SBC ANIM_CFG+3,X
   BMI at_done                             ; pos < max: still travelling
   LDA ANIM_CFG+2,X
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+3,X
   STA ANIM_WS+1,Y
   LDA #$80
   STA at_state
   LDA ANIM_CFG+7,X                        ; wait_at_B
   STA at_timer
   JMP at_done

at_wait:
   LDA at_timer                            ; wait 0 = HOLD FOREVER (DR doors
   BEQ at_done                             ; idle shut until pmove_use pokes
   DEC at_timer                            ; the state; 2026-08-14)
   BNE at_done
; wait expired: 0 -> 1 (A->B), 2 -> 3 (B->A); timer stays 0 while moving
   LDA at_state
   CLC
   ADC #$40
   STA at_state
   ZERO at_timer

at_done:
   LDA at_state
   ORA at_timer
   STA ANIM_WS+2,Y
   LDA ANIM_WS+1,Y
   CMP at_prevhi
   BEQ at_clean
   LDX at_m
   LDA ANIM_DIRTY
   ORA anim_bit2,X
   STA ANIM_DIRTY
at_clean:
   DEC at_m
   BMI at_end
   JMP at_loop
at_end:
   RTS
at_m:      .byte 0
at_t:      .byte 0
at_state:  .byte 0
at_timer:  .byte 0
at_prevhi: .byte 0
.endscope

anim_bit2:
   .byte 1,2,4,8,16,32

; --- anim_l0_worker: patch FHCH bytes + re-derive seg flags for mover
;     ANIM_CUR with value ANIM_VAL. ENTRY BANK-AGNOSTIC since 2026-08-19
;     (the hub is entered under WALK now): pages SEG itself for the TABL0
;     block walk and the header/BPAL patches, and flips to WALK around
;     every touch of the per-subsector front pages, which live in BANK B
;     with the rest of the SS planes. ---
; TABL0 block (gen_6502_tables): n_front, n_back, n_flag, n_vexpl, then
; n_front u16 FRONT-page addrs (bank B: SS_FH/SS_CH entries), n_back u16
; back-pair addrs (bank A: BPAL entries), then n_flag x (u16 seg-header
; flag addr, u16 FRONT-pair addr) covering every two-sided seg touching
; the sector; the BACK pair rides the flags address.
; The quad is SPLIT since 2026-08-17: fh/ch live on the per-subsector pages
; (ch is always fh + $100 — the pages abut) and bfh/bch in the header.
; pseudocode:
;   for each fhch addr: *addr = ANIM_VAL
;   for each flag entry:                       # packer's rules, post-patch
;     fh, ch = front[0], front[$100]
;     bfh, bch = BPAL_BFH[id], BPAL_BCH[id]   # id = the header's +SH_BPAL
;     f = *hdr & ~(SOLID|NEEDBT|NEEDBB)        # & $B3
;     if bch <= fh or bfh >= ch: f |= SOLID
;     else: if bch < ch: f |= NEEDBT ; if bfh > fh: f |= NEEDBB
;     *hdr = f
SEG_HIGH
anim_l0_worker:
.scope
   PAGE BANK_SEG                           ; TABL0 + headers + BPAL bank
   LDA ANIM_CUR
   ASL A
   TAY
   LDA ANIM_TABL0,Y
   STA zp_anim_p
   LDA ANIM_TABL0+1,Y
   STA zp_anim_p+1
   LDY #0
   LDA (zp_anim_p),Y                       ; n_front (bank-B SS-page addrs)
   STA alw_nf
   INY
   LDA (zp_anim_p),Y                       ; n_back (bank-A BPAL addrs)
   STA alw_nb
   INY
   LDA (zp_anim_p),Y                       ; n_flag
   STA alw_ng
   INY
   LDA (zp_anim_p),Y                       ; n_vexpl (jamb patch targets)
   STA alw_nv
   INY
; FRONT patches: the addr comes out of TABL0 under SEG, the byte lands in
; a bank-B SS page — flip per write (cold: <= 2 per mover)
alw_floop:
   LDA alw_nf
   BEQ alw_back
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
   PAGE BANK_WALK
.if ::C02
   LDA ANIM_VAL
   STA (zp_anim_w)                         ; non-indexed (the LDY died)
.else
   LDY #0
   LDA ANIM_VAL
   STA (zp_anim_w),Y
.endif
   PAGE BANK_SEG
   LDY alw_y
   DEC alw_nf
   JMP alw_floop
; BACK patches: BPAL entries, bank A — no flipping
alw_back:
   LDA alw_nb
   BEQ alw_flags
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
.if ::C02
   LDA ANIM_VAL
   STA (zp_anim_w)
.else
   LDY #0
   LDA ANIM_VAL
   STA (zp_anim_w),Y
.endif
   LDY alw_y
   DEC alw_nb
   JMP alw_back
alw_flags:
; per flag entry: u16 hdr flag addr, u16 FHCH quad addr
   LDA alw_ng
   BNE alw_gbody
   JMP alw_done
alw_gbody:
; walk the entry's THREE addresses out of the block first (Y is the block
; cursor and must survive to alw_y — read every u16 before touching it)
   LDA (zp_anim_p),Y
   STA alw_hdr
   INY
   LDA (zp_anim_p),Y
   STA alw_hdr+1
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w                            ; FRONT pair: fh here, ch at +$100
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
; front pair off the per-subsector pages (fh, then ch one page up — the two
; pages abut by construction; BANK B since 2026-08-19, so flip around it)
   PAGE BANK_WALK
   LDY #0
   LDA (zp_anim_w),Y
   STA alw_fh
   INC zp_anim_w+1
   LDA (zp_anim_w),Y
   STA alw_ch
   PAGE BANK_SEG
; back pair via the PALETTE (2026-08-17): the id byte sits in the SAME header
; as the flags byte, so its address is derived rather than carried — TABL0's
; 252 B budget has no room for a third u16 per entry. Mover-touching segs hold
; PRIVATE palette entries, so patching one never moves a neighbour.
   LDA alw_hdr
   CLC
   ADC #LAY_SH_BPAL - LAY_SH_FLAGS
   STA zp_anim_w
   LDA alw_hdr+1
   ADC #0
   STA zp_anim_w+1
   LDA (zp_anim_w),Y                        ; Y still 0: the palette id
   TAX
   LDA ROM_BPAL_BFH_C,X
   STA alw_bfh
   LDA ROM_BPAL_BCH_C,X
   STA alw_bch
; flags = old & ~(SOLID|NEEDBT|NEEDBB) = old & ~$4C (SOLID=$40)
   LDA alw_hdr
   STA zp_anim_w
   LDA alw_hdr+1
   STA zp_anim_w+1
.if ::C02
   LDA (zp_anim_w)                         ; non-indexed (Y untouched to the
.else                                     ;  writeback below — it forks too)
   LDY #0
   LDA (zp_anim_w),Y
.endif
   AND #$83                                ; ~(SOLID|NEEDBT|NEEDBB|STEPUP_T/B)
   STA alw_f
; SOLID iff bch <= fh  or  bfh >= ch
   LDA alw_bch
   SEC
   SBC alw_fh
   BMI alw_solid
   BEQ alw_solid
   LDA alw_bfh
   SEC
   SBC alw_ch
   BPL alw_solid
; portal, top: NEEDBT iff bch < ch ; STEPUP_T iff bch > ch (baked
; verdicts — the cascade dispatches on them, 2026-08-13)
   LDA alw_bch
   SEC
   SBC alw_ch
   BEQ alw_nott                            ; equal: neither
   BMI alw_bt
   LDA alw_f
   ORA #$10                                ; SF_STEPUP_T
   BNE alw_stt                             ; (always: bit set)
alw_bt:
   LDA alw_f
   ORA #$04                                ; SF_NEEDBT
alw_stt:
   STA alw_f
alw_nott:
; portal, bottom: NEEDBB iff bfh > fh ; STEPUP_B iff bfh < fh
   LDA alw_fh
   SEC
   SBC alw_bfh
   BEQ alw_nobb                            ; equal: neither
   BMI alw_bb
   LDA alw_f
   ORA #$20                                ; SF_STEPUP_B
   BNE alw_stb                             ; (always: bit set)
alw_bb:
   LDA alw_f
   ORA #$08                                ; SF_NEEDBB
alw_stb:
   STA alw_f
alw_nobb:
   JMP alw_wf
alw_solid:
   LDA alw_f
   ORA #$40                                ; SF_SOLID
   STA alw_f
alw_wf:
   LDA alw_f                               ; NEEDED: the BPL alw_nobb path
.if ::C02
   STA (zp_anim_w)                         ; arrives with the SBC result in A
.else
   STA (zp_anim_w),Y                       ; arrives with the SBC result in A
.endif
                                           ; (regscan false positive 2026-07-19
                                           ; — its meet missed the mid-chain
                                           ; branch; anim6502 caught it)
   LDY alw_y
   DEC alw_ng
   JMP alw_flags
alw_done:
; jamb VEXPL patches: u16 addrs of the entry byte holding the MOVING
; bound of an in-plane door/lift jamb span (VEXPL_LO or VEXPL_HI slot;
; gen_6502_tables). Value = ANIM_VAL, same as the FHCH patches. The
; targets live in BANK_C banked (VEXPL $A700/$A780) while the list is
; read from TABL0 under BANK_SEG — so each address is fetched first,
; then the write runs under a C excursion.
alw_vexpl:
   LDA alw_nv
   BEQ alw_ret
   LDA (zp_anim_p),Y
   STA zp_anim_w
   INY
   LDA (zp_anim_p),Y
   STA zp_anim_w+1
   INY
   STY alw_y
   PAGE BANK_C
.if ::C02
   LDA ANIM_VAL
   STA (zp_anim_w)
.else
   LDY #0
   LDA ANIM_VAL
   STA (zp_anim_w),Y
.endif
   PAGE BANK_SEG
   LDY alw_y
   DEC alw_nv
   JMP alw_vexpl
alw_ret:
   RTS
alw_nf:  .byte 0
alw_ng:  .byte 0
alw_nb:  .byte 0                         ; back-list count (front/back split)
alw_nv:  .byte 0
alw_y:   .byte 0
alw_hdr: .word 0
alw_fh:  .byte 0
alw_ch:  .byte 0
alw_bfh: .byte 0
alw_bch: .byte 0
alw_f:   .byte 0
.endscope

; ============================================================================
; sqr_fill — regenerate the quarter-square quad at $0200-$05FF.
; The quad lives on OS-owned pages (vector page + workspace) that no disc
; file can load, and never needs loading: f(n) = n*n >> 2 falls out of the
; recurrence f(n+1) = f(n) + ((n+1) >> 1). 1,024 bytes in ~13k cycles,
; once per boot. Callers: anim_init (walk_drv and the tube driver both
; come through it) and banked_boot's DRV directly (ENG_SQR_FILL).
; The harnesses poke identical values; bare-boot's FB compare against the
; poked model is the exactness gate. Clobbers A, X, Y, zp_anim_w pair.
; (The COLPORT copy-down used to live in this slot: the ports ship at
; $1A00 now, inside LOW / the tube CODE file. Do not resurrect $A900
; staging — it overlays the psi planes.)
; ============================================================================
SEG_HIGH
sqr_fill:
.scope
   LDA #0
   STA zp_anim_w                           ; f16 = 0
   STA zp_anim_w+1
   TAX                                     ; n = 0
   TAY                                     ; delta = 0
sq1:
   LDA zp_anim_w
   STA SQR_LO,X                            ; f(n) lo
   LDA zp_anim_w+1
   STA SQR_HI,X                            ; f(n) hi
   TXA
   LSR A
   BCC sq1e                                ; leaving odd n: delta+1
   INY                                     ;  (delta = (n+1) >> 1)
sq1e:
   TYA
   CLC
   ADC zp_anim_w
   STA zp_anim_w
   BCC sq1c
   INC zp_anim_w+1
sq1c:
   INX
   BNE sq1
sq2:                                       ; n = 256 + X (parity = X parity)
   LDA zp_anim_w
   STA SQR2_LO,X
   LDA zp_anim_w+1
   STA SQR2_HI,X
   TXA
   LSR A
   BCC sq2e
   INY
sq2e:
   TYA
   CLC
   ADC zp_anim_w
   STA zp_anim_w
   BCC sq2c
   INC zp_anim_w+1
sq2c:
   INX
   BNE sq2
   RTS
.endscope

; --- anim_init: load start state from CFG, mark all dirty, enable, and
;     point the subsector hook at the hub. Runs with BANK_L2 paged. ---
;   in : ANIM_CFG (+8 start88, +10 packed start state/timer)
;   out: ANIM_WS seeded (all 6 movers), ANIM_DIRTY = $3F (every mover patches
;        on first visibility, even before any motion), ANIM_ENABLE = 1,
;        anim_ss_hook operand SMC-patched -> anim_hub, ANIM_SSMASK copied
;        down from its L2 staging page (banked only — see below).
SEG_HIGH
anim_init:
.scope
; sqr fill first — see sqr_fill below; a JSR so the one-frame bare-boot
; driver (banked_boot DRV), which never touches anims, can call the fill
; alone via ENG_SQR_FILL.
   JSR sqr_fill
; (SSMASK copy-down DELETED 2026-08-19: the hub reads the shipped page
; in place — banked $B400 under the WALK bank it is entered with, flat
; $E500. The whole failure class the copy carried — the 355c126 frozen
; doors, the $B4DD tail drag, the COLIDX-in-the-tail scar — dies with
; it; jsbeeb anim_live remains the catcher for shipped-mask breakage.)
   LDA #5
   STA ai_midx
ai_m:
   LDA ai_midx
   ASL A
   CLC
   ADC ai_midx
   TAY                                     ; m*3
   LDA ai_midx
   ASL A
   ASL A
   STA ai_t                                ; m*4
   ASL A                                   ; m*8
   CLC
   ADC ai_t                                ; m*12
   TAX
   LDA ANIM_CFG+8,X                        ; start pos (8.8 prescaled)
   STA ANIM_WS+0,Y
   LDA ANIM_CFG+9,X
   STA ANIM_WS+1,Y
   LDA ANIM_CFG+10,X                       ; packed start state/timer
   STA ANIM_WS+2,Y
   DEC ai_midx
   BPL ai_m
   LDA #$3F
   STA ANIM_DIRTY
   LDA #1
   STA ANIM_ENABLE
   LDA #<anim_hub
   STA anim_ss_hook+1
   LDA #>anim_hub
   STA anim_ss_hook+2
   RTS
ai_t:    .byte 0
ai_midx: .byte 0
.endscope


SEG_CODE
