; GENERATED by tools/gen_pm_sincos.py — DO NOT EDIT.
; pm_frame movement trig, 8-BIT (fp.fp_sincos, the view trig):
; first-quadrant sine, i = 0..16 (5.625 deg steps), unity folded
; to 255.  pmf_unit derives (cmag,cneg,smag,sneg) by quadrant.
SEG_PMB3
pm_sin8:
   .byte $00, $19, $32, $4A, $62, $79, $8E, $A2, $B5
   .byte $C6, $D5, $E2, $ED, $F5, $FB, $FF, $FF
