; GENERATED by tools/gen_pm_sincos.py — DO NOT EDIT.
; 64 x 2 packed count-native trig (fp.fp_sincos5): sin,cos as
; mag6|neg<<6, unity pre-folded to mag 32. pm_frame indexes
; via zp_pm_p (pmf_unit).
SEG_PMB3
pm_sincos:
   .byte $00, $20, $03, $20, $06, $1F, $09, $1F, $0C, $1E, $0F, $1C, $12, $1B, $14, $19
   .byte $17, $17, $19, $14, $1B, $12, $1C, $0F, $1E, $0C, $1F, $09, $1F, $06, $20, $03
   .byte $20, $00, $20, $43, $1F, $46, $1F, $49, $1E, $4C, $1C, $4F, $1B, $52, $19, $54
   .byte $17, $57, $14, $59, $12, $5B, $0F, $5C, $0C, $5E, $09, $5F, $06, $5F, $03, $60
   .byte $00, $60, $43, $60, $46, $5F, $49, $5F, $4C, $5E, $4F, $5C, $52, $5B, $54, $59
   .byte $57, $57, $59, $54, $5B, $52, $5C, $4F, $5E, $4C, $5F, $49, $5F, $46, $60, $43
   .byte $60, $00, $60, $03, $5F, $06, $5F, $09, $5E, $0C, $5C, $0F, $5B, $12, $59, $14
   .byte $57, $17, $54, $19, $52, $1B, $4F, $1C, $4C, $1E, $49, $1F, $46, $1F, $43, $20
