#!/usr/bin/env python3
"""Generate src/bsp/pm_sincos.s — pm_frame's movement trig table.

8-BIT since 2026-09-03 (was the retired 5-bit round-and-promote grid):
ONE SOURCE, fp.fp_sincos — the renderer's own 8-bit trig, so a walk
goes exactly where the view looks (5-bit magnitudes were up to 3% off
in speed and 1.5 deg off in direction).  Storage is the FIRST-QUADRANT
SINE only: pm_sin8[i] = round(sin(i * 5.625 deg) * 256) for i = 0..16,
unity (i = 16, and the 90-deg row of fp_sincos where round() >= 256)
FOLDED TO 255 so every magnitude fits a byte (the cardinal step is
143*255>>8 = 142 counts instead of 143: 0.4-0.7%).  pmf_unit derives
the four (cmag, cneg, smag, sneg) from the quadrant:
   q = a >> 4, i = a & 15
   q even: smag = S[i],    cmag = S[16-i]      q odd: swapped
   sneg = q >> 1,  cneg = (q >> 1) ^ (q & 1)
(colmap._unit8 is the bit-exact mirror.)  17 bytes, CODE.
Regenerate after any trig change: python3 tools/gen_pm_sincos.py
"""
import os, sys
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
sys.path.insert(0, '.')
import fp

S = []
for i in range(17):
    sm, sn, su, cm, cn, cu = fp.fp_sincos(i * 4)
    S.append(255 if su else sm)
assert S[0] == 0 and S[16] == 255 and all(0 <= v <= 255 for v in S)
assert S == sorted(S), 'first-quadrant sine must be monotone'

with open('src/bsp/pm_sincos.s', 'w') as f:
    f.write('; GENERATED by tools/gen_pm_sincos.py — DO NOT EDIT.\n'
            '; pm_frame movement trig, 8-BIT (fp.fp_sincos, the view trig):\n'
            '; first-quadrant sine, i = 0..16 (5.625 deg steps), unity folded\n'
            '; to 255.  pmf_unit derives (cmag,cneg,smag,sneg) by quadrant.\n'
            'SEG_PMB3\n'
            'pm_sin8:\n')
    f.write('   .byte ' + ', '.join(f'${v:02X}' for v in S[:9]) + '\n')
    f.write('   .byte ' + ', '.join(f'${v:02X}' for v in S[9:]) + '\n')
print('wrote src/bsp/pm_sincos.s (17 bytes):', S)
