#!/usr/bin/env python3
"""Generate src/bsp/pm_sincos.s — pm_frame's packed 64x2 count-native
trig table. ONE SOURCE: fp.fp_sincos5 (the canonical 5-bit trig, same
function the model's colmap._unit5 reads).
Row (2 bytes): sin, cos — each mag6 | neg<<6, with UNITY FOLDED to
mag 32 at bake time so the 6502 decode is branchless (AND #$3F mag,
bit 6 sign). Segment PMB3 (bank B $B348 banked / the flat PMBF region).
Regenerate after any trig-grid change: python3 tools/gen_pm_sincos.py
"""
import os, sys
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
sys.path.insert(0, '.')
import fp

rows = []
for i in range(64):
    sm, sn, so, cm, cn, co = fp.fp_sincos5((i * 4) & 0xFF)
    s = (32 if so else sm) | (0x40 if sn else 0)
    c = (32 if co else cm) | (0x40 if cn else 0)
    rows.append((s, c))

with open('src/bsp/pm_sincos.s', 'w') as f:
    f.write('; GENERATED by tools/gen_pm_sincos.py — DO NOT EDIT.\n'
            '; 64 x 2 packed count-native trig (fp.fp_sincos5): sin,cos as\n'
            '; mag6|neg<<6, unity pre-folded to mag 32. pm_frame indexes\n'
            '; via zp_pm_p (pmf_unit).\n'
            'SEG_PMB3\n'
            'pm_sincos:\n')
    for i in range(0, 64, 8):
        f.write('   .byte ' + ', '.join(
            f'${s:02X}, ${c:02X}' for s, c in rows[i:i+8]) + '\n')
print('wrote src/bsp/pm_sincos.s (128 bytes)')
