#!/usr/bin/env python3
"""Generate the cross-language ABI constant files from ONE table.

Every address that crosses a language boundary (ca65 engine <-> beebasm
drivers <-> Python harness/builders) lives HERE and nowhere else. Private
copies of these addresses have shipped three broken-disc bugs (vxc_ab,
the HUD var block, the test-harness pokes) — see project_bank_reshuffle.

Outputs (all checked in; regenerate after editing the table):
  src/abi.inc    ca65   (.if ::BANKED variants where flat differs)
  abi_beeb.inc   beebasm (banked values only — discs are banked builds)
  abi.py         Python  (NAME = banked value; NAME_FLAT where it differs)

Run: python3 tools/gen_abi.py   (from the repo root)
"""
import os
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

# (name, banked, flat_or_None_if_same_or_meaningless, comment)
ABI = [
    ('BANK_L0',        4,      None, 'sideways bank: level data (SoA, seg_hdr, FHCH, TABL0)'),
    ('BANK_C',         6,      None, 'sideways bank: clipper + rasteriser + HUD'),
    ('BANK_L2',        7,      None, 'sideways bank: angle/bbox/recip/verts/RCACHE/VWHC/CFG'),
    ('ENGINE_JT',      0x2C00, 0x3670, 'driver-facing jump table = MAIN segment head (link-asserted)'),
    ('JT_VIEW_SETUP',  'ENGINE_JT+$06', None, 'br_view_setup'),
    ('JT_RENDER_FRAME','ENGINE_JT+$12', None, 'br_render_frame'),
    ('JT_ANIM_TICK',   'ENGINE_JT+$18', None, 'anim_tick (PAGE BANK_L2 first)'),
    ('JT_ANIM_INIT',   'ENGINE_JT+$1B', None, 'anim_init (PAGE BANK_L2 first)'),
    ('CLIP_JT',        0x8000, 0x2000, 'clipper jump table; entry 0 = span_init'),
    ('HUD_ENTRY',      0xA400, None, 'hud_draw (bank C window)'),
    ('BCA_WS',         0x1B40, 0xFA00, 'angle-module bbox workspace (box vals at +$10..$17)'),
    ('BCA_AB',         'BCA_WS+$2F', None, 'view angle byte, poked per frame by driver/harness'),
    ('SQR_BASE',       0x1C00, 0xA500, 'quarter-square tables: lo,hi,2lo,2hi = 4 pages'),
    # REORDERED 2026-07-12: lo pages CONTIGUOUS (f(0..510) linear), then
    # hi pages — rot_core's frame-constant-mag SMC bases index across the
    # 255 boundary without a window branch. Classic sqr/sqr2 split users
    # are unaffected (the equates still name both windows).
    ('SQR_LO',         'SQR_BASE+$000', None, 'qsqr lo bytes (f 0..255)'),
    ('SQR2_LO',        'SQR_BASE+$100', None, 'qsqr lo bytes (f 256..510)'),
    ('SQR_HI',         'SQR_BASE+$200', None, 'qsqr hi bytes (f 0..255)'),
    ('SQR2_HI',        'SQR_BASE+$300', None, 'qsqr hi bytes (f 256..510)'),
    ('DRV_ORG',        0x2000, None, 'walk/anim driver entry (!BOOT CALLs this)'),
    ('DRV_VARS',       0x2180, None, 'walk driver variable block (layout below)'),
    ('DV_ANGIDX',      'DRV_VARS+0',  None, 'view angle index 0..63 (angle byte = idx*4)'),
    ('DV_BACKHI',      'DRV_VARS+1',  None, 'hidden-buffer page hi ($58/$6C)'),
    ('DV_PXF',         'DRV_VARS+2',  None, 'player x 8.8 prescaled, 24-bit: frac'),
    ('DV_PXL',         'DRV_VARS+3',  None, '... int lo'),
    ('DV_PXH',         'DRV_VARS+4',  None, '... int hi'),
    ('DV_PYF',         'DRV_VARS+5',  None, 'player y frac'),
    ('DV_PYL',         'DRV_VARS+6',  None, '... int lo'),
    ('DV_PYH',         'DRV_VARS+7',  None, '... int hi'),
    ('DV_JIDX',        'DRV_VARS+8',  None, 'vsync journal index'),
    ('DV_HUD_EN',      'DRV_VARS+9',  None, 'debug HUD on/off (H toggles)'),
    ('DV_HUD_PREV',    'DRV_VARS+10', None, 'H-key debounce state'),
    ('DRV_GLUE',       0x21A0, None, 'anim/HUD glue pocket'),
    ('DRV_TAB',        0x2200, None, 'sincos table overlay: 64 x 8 bytes'),
    ('DRV_CLR',        0x2400, None, 'unrolled clears + input block'),
    ('D_ENABLE',       0x05FE, None, 'forward-coherence bbox cache master switch'),
    ('D_FWD',          0x05FF, None, 'per-frame flag: move was forward-only'),
    ('VXC_STATE',      0x05A0, None, 'VXC valid bitmap + state block'),
    ('VXC_STATE_LEN',  0x60,   None, 'bytes to zero at boot'),
    ('VXC_ENABLE',     0x05DB, None, 'translation vertex cache switch'),
    ('RCACHE_STATE',   0xB460, 0xF100, 'rotation cache header+bitmaps (flat: $F100; carve freed 2026-07-15)'),
    ('RCACHE_STATE_LEN',0x89,  None, 'bytes to zero at boot'),
    ('RCACHE_ENABLE',  0xB4E8, 0xF188, 'rotation-coherence bca cache switch (STATE+$88)'),
    ('JBASE',          0x1A00, None, 'vsync journal (dead boot-loader memory)'),
    ('SCREEN0',        0x5800, None, 'framebuffer 0'),
    ('SCREEN1',        0x6C00, None, 'framebuffer 1'),
]


def fmt_val(v, hexer):
    if isinstance(v, str):
        return v.replace('$', hexer) if hexer != '$' else v
    return f'{hexer}{v:04X}' if v > 9 else str(v)


HDR = ('GENERATED by tools/gen_abi.py — DO NOT EDIT. One table, three\n'
       'projections: private copies of these addresses are forbidden.')

with open('src/abi.inc', 'w') as f:
    f.write(f'; {HDR.replace(chr(10), chr(10)+"; ")}\n')
    f.write('.ifndef ABI_INC_GUARD\nABI_INC_GUARD = 1\n')
    for name, bank, flat, comment in ABI:
        if flat is None or flat == bank:
            f.write(f'{name} = {fmt_val(bank, "$")}'.ljust(40) + f'; {comment}\n')
        else:
            f.write(f'.if ::BANKED\n{name} = {fmt_val(bank, "$")}'.ljust(40)
                    + f'; {comment}\n.else\n{name} = {fmt_val(flat, "$")}\n.endif\n')
    f.write('.endif\n')

with open('abi_beeb.inc', 'w') as f:
    f.write(f'\\ {HDR.replace(chr(10), chr(10)+chr(92)+" ")}\n')
    f.write('\\ (banked values only: the discs are banked builds)\n')
    for name, bank, flat, comment in ABI:
        f.write(f'{name} = {fmt_val(bank, "&")}'.ljust(40) + f'\\ {comment}\n')

with open('abi.py', 'w') as f:
    f.write(f'# {HDR.replace(chr(10), chr(10)+"# ")}\n')
    env = {}
    for name, bank, flat, comment in ABI:
        v = bank
        if isinstance(v, str):
            v = eval(v.replace('$', '0x'), {}, env)
        env[name] = v
        f.write(f'{name} = 0x{v:04X}  # {comment}\n' if v > 9
                else f'{name} = {v}  # {comment}\n')
        if flat is not None and flat != bank:
            f.write(f'{name}_FLAT = 0x{flat:04X}\n')

print('wrote src/abi.inc, abi_beeb.inc, abi.py')
